// Code generated by MockGen. DO NOT EDIT.
// Source: exporter_module/internal/server/interfaces (interfaces: Ansible,API,Database,Metrics,Network,Server,Manager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks exporter_module/internal/server/interfaces Ansible,API,Database,Metrics,Network,Server,Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	interfaces "exporter_module/internal/server/interfaces"
	reflect "reflect"

	prometheus "github.com/prometheus/client_golang/prometheus"
	gomock "go.uber.org/mock/gomock"
)

// MockAnsible is a mock of Ansible interface.
type MockAnsible struct {
	ctrl     *gomock.Controller
	recorder *MockAnsibleMockRecorder
	isgomock struct{}
}

// MockAnsibleMockRecorder is the mock recorder for MockAnsible.
type MockAnsibleMockRecorder struct {
	mock *MockAnsible
}

// NewMockAnsible creates a new mock instance.
func NewMockAnsible(ctrl *gomock.Controller) *MockAnsible {
	mock := &MockAnsible{ctrl: ctrl}
	mock.recorder = &MockAnsibleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnsible) EXPECT() *MockAnsibleMockRecorder {
	return m.recorder
}

// CmdExecute mocks base method.
func (m *MockAnsible) CmdExecute(ctx context.Context, remoteHost, remotUser, sshPrivateKeyFile, playbook, extraArgs string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdExecute", ctx, remoteHost, remotUser, sshPrivateKeyFile, playbook, extraArgs)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CmdExecute indicates an expected call of CmdExecute.
func (mr *MockAnsibleMockRecorder) CmdExecute(ctx, remoteHost, remotUser, sshPrivateKeyFile, playbook, extraArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdExecute", reflect.TypeOf((*MockAnsible)(nil).CmdExecute), ctx, remoteHost, remotUser, sshPrivateKeyFile, playbook, extraArgs)
}

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// APIExecuteJWTAUth mocks base method.
func (m *MockAPI) APIExecuteJWTAUth(ctx context.Context, method, url, apiname, jwt, queryParameter string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIExecuteJWTAUth", ctx, method, url, apiname, jwt, queryParameter)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIExecuteJWTAUth indicates an expected call of APIExecuteJWTAUth.
func (mr *MockAPIMockRecorder) APIExecuteJWTAUth(ctx, method, url, apiname, jwt, queryParameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIExecuteJWTAUth", reflect.TypeOf((*MockAPI)(nil).APIExecuteJWTAUth), ctx, method, url, apiname, jwt, queryParameter)
}

// APIExecuteUserAuth mocks base method.
func (m *MockAPI) APIExecuteUserAuth(ctx context.Context, method, url, apiname, loginUser, loginPass, queryParameter string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIExecuteUserAuth", ctx, method, url, apiname, loginUser, loginPass, queryParameter)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIExecuteUserAuth indicates an expected call of APIExecuteUserAuth.
func (mr *MockAPIMockRecorder) APIExecuteUserAuth(ctx, method, url, apiname, loginUser, loginPass, queryParameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIExecuteUserAuth", reflect.TypeOf((*MockAPI)(nil).APIExecuteUserAuth), ctx, method, url, apiname, loginUser, loginPass, queryParameter)
}

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Finalize mocks base method.
func (m *MockDatabase) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockDatabaseMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockDatabase)(nil).Finalize))
}

// Init mocks base method.
func (m *MockDatabase) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDatabaseMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDatabase)(nil).Init))
}

// SelectNwSwitchTable mocks base method.
func (m *MockDatabase) SelectNwSwitchTable() ([]interfaces.NetworkTargetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectNwSwitchTable")
	ret0, _ := ret[0].([]interfaces.NetworkTargetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectNwSwitchTable indicates an expected call of SelectNwSwitchTable.
func (mr *MockDatabaseMockRecorder) SelectNwSwitchTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectNwSwitchTable", reflect.TypeOf((*MockDatabase)(nil).SelectNwSwitchTable))
}

// SelectServerTable mocks base method.
func (m *MockDatabase) SelectServerTable() ([]interfaces.ServerTargetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectServerTable")
	ret0, _ := ret[0].([]interfaces.ServerTargetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectServerTable indicates an expected call of SelectServerTable.
func (mr *MockDatabaseMockRecorder) SelectServerTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectServerTable", reflect.TypeOf((*MockDatabase)(nil).SelectServerTable))
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMetrics) Delete(metrics *prometheus.GaugeVec, label prometheus.Labels) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", metrics, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMetricsMockRecorder) Delete(metrics, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMetrics)(nil).Delete), metrics, label)
}

// Finalize mocks base method.
func (m *MockMetrics) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockMetricsMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockMetrics)(nil).Finalize))
}

// Init mocks base method.
func (m *MockMetrics) Init(metrics []*prometheus.GaugeVec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockMetricsMockRecorder) Init(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockMetrics)(nil).Init), metrics)
}

// Write mocks base method.
func (m *MockMetrics) Write(metrics *prometheus.GaugeVec, label prometheus.Labels, value float64, writedMetrics *[]interfaces.MetricLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", metrics, label, value, writedMetrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockMetricsMockRecorder) Write(metrics, label, value, writedMetrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMetrics)(nil).Write), metrics, label, value, writedMetrics)
}

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
	isgomock struct{}
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockNetwork) Collection(targetList []interfaces.NetworkTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collection", targetList)
}

// Collection indicates an expected call of Collection.
func (mr *MockNetworkMockRecorder) Collection(targetList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockNetwork)(nil).Collection), targetList)
}

// Finalize mocks base method.
func (m *MockNetwork) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockNetworkMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockNetwork)(nil).Finalize))
}

// Init mocks base method.
func (m *MockNetwork) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockNetworkMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockNetwork)(nil).Init))
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// Colloction mocks base method.
func (m *MockServer) Colloction(targetList []interfaces.ServerTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Colloction", targetList)
}

// Colloction indicates an expected call of Colloction.
func (mr *MockServerMockRecorder) Colloction(targetList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Colloction", reflect.TypeOf((*MockServer)(nil).Colloction), targetList)
}

// Finalize mocks base method.
func (m *MockServer) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockServerMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockServer)(nil).Finalize))
}

// Init mocks base method.
func (m *MockServer) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockServerMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockServer)(nil).Init))
}

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// NetworkList mocks base method.
func (m *MockManager) NetworkList(arg0 []interfaces.NetworkTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NetworkList", arg0)
}

// NetworkList indicates an expected call of NetworkList.
func (mr *MockManagerMockRecorder) NetworkList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkList", reflect.TypeOf((*MockManager)(nil).NetworkList), arg0)
}

// SetP2POn mocks base method.
func (m *MockManager) SetP2POn(arg0 []interfaces.ServerTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetP2POn", arg0)
}

// SetP2POn indicates an expected call of SetP2POn.
func (mr *MockManagerMockRecorder) SetP2POn(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetP2POn", reflect.TypeOf((*MockManager)(nil).SetP2POn), arg0)
}

// ServerList mocks base method.
func (m *MockManager) ServerList(arg0 []interfaces.ServerTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServerList", arg0)
}

// ServerList indicates an expected call of ServerList.
func (mr *MockManagerMockRecorder) ServerList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerList", reflect.TypeOf((*MockManager)(nil).ServerList), arg0)
}
