// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/proto/cdi_interface.proto

package protocdi

import (
	proto "common/api/proto"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for detail error code
type DetailCode int32

const (
	DetailCode_ZERO                    DetailCode = 0
	DetailCode_IF_PARAMETER_INVALID    DetailCode = 41
	DetailCode_UNSUPPORT_PRODUCT       DetailCode = 42
	DetailCode_CDI_ENVIRONMENT_ERROR   DetailCode = 61
	DetailCode_CDI_COMMAND_ERROR_V_1_0 DetailCode = 71
	DetailCode_CDI_COMMAND_ERROR_V_1_1 DetailCode = 72
	DetailCode_CDI_RESPONSE_INVALID    DetailCode = 81
)

// Enum value maps for DetailCode.
var (
	DetailCode_name = map[int32]string{
		0:  "ZERO",
		41: "IF_PARAMETER_INVALID",
		42: "UNSUPPORT_PRODUCT",
		61: "CDI_ENVIRONMENT_ERROR",
		71: "CDI_COMMAND_ERROR_V_1_0",
		72: "CDI_COMMAND_ERROR_V_1_1",
		81: "CDI_RESPONSE_INVALID",
	}
	DetailCode_value = map[string]int32{
		"ZERO":                    0,
		"IF_PARAMETER_INVALID":    41,
		"UNSUPPORT_PRODUCT":       42,
		"CDI_ENVIRONMENT_ERROR":   61,
		"CDI_COMMAND_ERROR_V_1_0": 71,
		"CDI_COMMAND_ERROR_V_1_1": 72,
		"CDI_RESPONSE_INVALID":    81,
	}
)

func (x DetailCode) Enum() *DetailCode {
	p := new(DetailCode)
	*p = x
	return p
}

func (x DetailCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetailCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cdi_interface_proto_enumTypes[0].Descriptor()
}

func (DetailCode) Type() protoreflect.EnumType {
	return &file_api_proto_cdi_interface_proto_enumTypes[0]
}

func (x DetailCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetailCode.Descriptor instead.
func (DetailCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{0}
}

// message of Product information
type ProductInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`                              // vendor name
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // product name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // version
	Os            *string                `protobuf:"bytes,4,opt,name=os,proto3,oneof" json:"os,omitempty"`                                // os info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInformation) Reset() {
	*x = ProductInformation{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInformation) ProtoMessage() {}

func (x *ProductInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInformation.ProtoReflect.Descriptor instead.
func (*ProductInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInformation) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ProductInformation) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProductInformation) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

// message of CDI information
type CdiInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteHost    string                 `protobuf:"bytes,1,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"` // host name or ip address
	RemoteUser    string                 `protobuf:"bytes,2,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"` // login user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CdiInformation) Reset() {
	*x = CdiInformation{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CdiInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CdiInformation) ProtoMessage() {}

func (x *CdiInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CdiInformation.ProtoReflect.Descriptor instead.
func (*CdiInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{1}
}

func (x *CdiInformation) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *CdiInformation) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

// message of Resource Modify Requests
type ResourceModifyRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`                                         // operation type
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"` // resource name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceModifyRequests) Reset() {
	*x = ResourceModifyRequests{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceModifyRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceModifyRequests) ProtoMessage() {}

func (x *ResourceModifyRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceModifyRequests.ProtoReflect.Descriptor instead.
func (*ResourceModifyRequests) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceModifyRequests) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ResourceModifyRequests) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

// Request message for MachineCreate
type MachineCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	CdiInfo        *CdiInformation        `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                            // CDI information
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // group name
	MachineName    string                 `protobuf:"bytes,4,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`                // machine name
	ResourceList   []string               `protobuf:"bytes,5,rep,name=resource_list,json=resourceList,proto3" json:"resource_list,omitempty"`             // resource list
	ExtraParameter *string                `protobuf:"bytes,6,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineCreateRequest) Reset() {
	*x = MachineCreateRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateRequest) ProtoMessage() {}

func (x *MachineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateRequest.ProtoReflect.Descriptor instead.
func (*MachineCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{3}
}

func (x *MachineCreateRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineCreateRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *MachineCreateRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MachineCreateRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *MachineCreateRequest) GetResourceList() []string {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

func (x *MachineCreateRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineCreate
type MachineCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Accept or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineCreateReply) Reset() {
	*x = MachineCreateReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCreateReply) ProtoMessage() {}

func (x *MachineCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCreateReply.ProtoReflect.Descriptor instead.
func (*MachineCreateReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{4}
}

func (x *MachineCreateReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineCreateReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for MachineDestroy
type MachineDestroyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	CdiInfo        *CdiInformation        `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                            // CDI information
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // group name
	MachineName    string                 `protobuf:"bytes,4,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`                // machine name
	ExtraParameter *string                `protobuf:"bytes,5,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineDestroyRequest) Reset() {
	*x = MachineDestroyRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDestroyRequest) ProtoMessage() {}

func (x *MachineDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDestroyRequest.ProtoReflect.Descriptor instead.
func (*MachineDestroyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{5}
}

func (x *MachineDestroyRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineDestroyRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *MachineDestroyRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MachineDestroyRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *MachineDestroyRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineDestroy
type MachineDestroyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Accept or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDestroyReply) Reset() {
	*x = MachineDestroyReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDestroyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDestroyReply) ProtoMessage() {}

func (x *MachineDestroyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDestroyReply.ProtoReflect.Descriptor instead.
func (*MachineDestroyReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{6}
}

func (x *MachineDestroyReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineDestroyReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for MachineShow
type MachineShowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	CdiInfo        *CdiInformation        `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                            // CDI information
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // group name
	MachineName    string                 `protobuf:"bytes,4,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`                // machine name
	ExtraParameter *string                `protobuf:"bytes,5,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineShowRequest) Reset() {
	*x = MachineShowRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineShowRequest) ProtoMessage() {}

func (x *MachineShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineShowRequest.ProtoReflect.Descriptor instead.
func (*MachineShowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{7}
}

func (x *MachineShowRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineShowRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *MachineShowRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MachineShowRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *MachineShowRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineShow
type MachineShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Success or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // machine info(JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineShowReply) Reset() {
	*x = MachineShowReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineShowReply) ProtoMessage() {}

func (x *MachineShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineShowReply.ProtoReflect.Descriptor instead.
func (*MachineShowReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{8}
}

func (x *MachineShowReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineShowReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MachineShowReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Request message for ResourceList
type ResourceListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	CdiInfo        *CdiInformation        `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                            // CDI information
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                      // group name
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceListRequest) Reset() {
	*x = ResourceListRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceListRequest) ProtoMessage() {}

func (x *ResourceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceListRequest.ProtoReflect.Descriptor instead.
func (*ResourceListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceListRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *ResourceListRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *ResourceListRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ResourceListRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for ResourceList
type ResourceListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Success or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // resource list info(JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceListReply) Reset() {
	*x = ResourceListReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceListReply) ProtoMessage() {}

func (x *ResourceListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceListReply.ProtoReflect.Descriptor instead.
func (*ResourceListReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceListReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *ResourceListReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResourceListReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Request message for ResourceShow
type ResourceShowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	CdiInfo        *CdiInformation        `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                            // CDI information
	ResourceName   string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`             // resource name
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceShowRequest) Reset() {
	*x = ResourceShowRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShowRequest) ProtoMessage() {}

func (x *ResourceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShowRequest.ProtoReflect.Descriptor instead.
func (*ResourceShowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceShowRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *ResourceShowRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *ResourceShowRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ResourceShowRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for ResourceShow
type ResourceShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Success or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // resource info(JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceShowReply) Reset() {
	*x = ResourceShowReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShowReply) ProtoMessage() {}

func (x *ResourceShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShowReply.ProtoReflect.Descriptor instead.
func (*ResourceShowReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceShowReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *ResourceShowReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResourceShowReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Request message for CardScaling
type CardScalingRequest struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	ProductInfo            *ProductInformation       `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                                    // Product information
	CdiInfo                *CdiInformation           `protobuf:"bytes,2,opt,name=cdi_info,json=cdiInfo,proto3" json:"cdi_info,omitempty"`                                                // CDI information
	GroupName              string                    `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                                          // group name
	MachineName            string                    `protobuf:"bytes,4,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`                                    // machine name
	ResourceModifyRequests []*ResourceModifyRequests `protobuf:"bytes,5,rep,name=resource_modify_requests,json=resourceModifyRequests,proto3" json:"resource_modify_requests,omitempty"` // Resources for modify
	ExtraParameter         *string                   `protobuf:"bytes,6,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"`                     // Product extension parameters
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardScalingRequest) Reset() {
	*x = CardScalingRequest{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardScalingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardScalingRequest) ProtoMessage() {}

func (x *CardScalingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardScalingRequest.ProtoReflect.Descriptor instead.
func (*CardScalingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{13}
}

func (x *CardScalingRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *CardScalingRequest) GetCdiInfo() *CdiInformation {
	if x != nil {
		return x.CdiInfo
	}
	return nil
}

func (x *CardScalingRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CardScalingRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *CardScalingRequest) GetResourceModifyRequests() []*ResourceModifyRequests {
	if x != nil {
		return x.ResourceModifyRequests
	}
	return nil
}

func (x *CardScalingRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for CardScaling
type CardScalingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (Accept or Error)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardScalingReply) Reset() {
	*x = CardScalingReply{}
	mi := &file_api_proto_cdi_interface_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardScalingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardScalingReply) ProtoMessage() {}

func (x *CardScalingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cdi_interface_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardScalingReply.ProtoReflect.Descriptor instead.
func (*CardScalingReply) Descriptor() ([]byte, []int) {
	return file_api_proto_cdi_interface_proto_rawDescGZIP(), []int{14}
}

func (x *CardScalingReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *CardScalingReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_cdi_interface_proto protoreflect.FileDescriptor

const file_api_proto_cdi_interface_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/cdi_interface.proto\x12\bprotocdi\x1a\x17validate/validate.proto\x1a'common/api/proto/common_interface.proto\"\xb5\x01\n" +
	"\x12ProductInformation\x12\"\n" +
	"\x06vendor\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\x06vendor\x12-\n" +
	"\fproduct_name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\vproductName\x12$\n" +
	"\aversion\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\aversion\x12\x1f\n" +
	"\x02os\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01H\x00R\x02os\x88\x01\x01B\x05\n" +
	"\x03_os\"i\n" +
	"\x0eCdiInformation\x12+\n" +
	"\vremote_host\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\n" +
	"remoteHost\x12*\n" +
	"\vremote_user\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\n" +
	"remoteUser\"c\n" +
	"\x16ResourceModifyRequests\x12\x19\n" +
	"\x02op\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\x02op\x12.\n" +
	"\rresource_name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\fresourceName\"\xf2\x02\n" +
	"\x14MachineCreateRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12(\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\tgroupName\x12,\n" +
	"\fmachine_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x16R\vmachineName\x126\n" +
	"\rresource_list\x18\x05 \x03(\tB\x11\xfaB\x0e\x92\x01\v\b\x01\"\ar\x05\x10\x01\x18\x80\x01R\fresourceList\x12,\n" +
	"\x0fextra_parameter\x18\x06 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"u\n" +
	"\x12MachineCreateReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xbb\x02\n" +
	"\x15MachineDestroyRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12(\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\tgroupName\x12,\n" +
	"\fmachine_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x16R\vmachineName\x12,\n" +
	"\x0fextra_parameter\x18\x05 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"v\n" +
	"\x13MachineDestroyReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xb8\x02\n" +
	"\x12MachineShowRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12(\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\tgroupName\x12,\n" +
	"\fmachine_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x16R\vmachineName\x12,\n" +
	"\x0fextra_parameter\x18\x05 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x87\x01\n" +
	"\x10MachineShowReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB\t\n" +
	"\a_result\"\x8b\x02\n" +
	"\x13ResourceListRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12(\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\tgroupName\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x88\x01\n" +
	"\x11ResourceListReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB\t\n" +
	"\a_result\"\x91\x02\n" +
	"\x13ResourceShowRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12.\n" +
	"\rresource_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\fresourceName\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x88\x01\n" +
	"\x11ResourceShowReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB\t\n" +
	"\a_result\"\x9e\x03\n" +
	"\x12CardScalingRequest\x12I\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1c.protocdi.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12=\n" +
	"\bcdi_info\x18\x02 \x01(\v2\x18.protocdi.CdiInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acdiInfo\x12(\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\tgroupName\x12,\n" +
	"\fmachine_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x16R\vmachineName\x12d\n" +
	"\x18resource_modify_requests\x18\x05 \x03(\v2 .protocdi.ResourceModifyRequestsB\b\xfaB\x05\x92\x01\x02\b\x01R\x16resourceModifyRequests\x12,\n" +
	"\x0fextra_parameter\x18\x06 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"s\n" +
	"\x10CardScalingReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result*\xb6\x01\n" +
	"\n" +
	"DetailCode\x12\b\n" +
	"\x04ZERO\x10\x00\x12\x18\n" +
	"\x14IF_PARAMETER_INVALID\x10)\x12\x15\n" +
	"\x11UNSUPPORT_PRODUCT\x10*\x12\x19\n" +
	"\x15CDI_ENVIRONMENT_ERROR\x10=\x12\x1b\n" +
	"\x17CDI_COMMAND_ERROR_V_1_0\x10G\x12\x1b\n" +
	"\x17CDI_COMMAND_ERROR_V_1_1\x10H\x12\x18\n" +
	"\x14CDI_RESPONSE_INVALID\x10Q2\xdc\x03\n" +
	"\x03Cdi\x12O\n" +
	"\rMachineCreate\x12\x1e.protocdi.MachineCreateRequest\x1a\x1c.protocdi.MachineCreateReply\"\x00\x12R\n" +
	"\x0eMachineDestroy\x12\x1f.protocdi.MachineDestroyRequest\x1a\x1d.protocdi.MachineDestroyReply\"\x00\x12I\n" +
	"\vMachineShow\x12\x1c.protocdi.MachineShowRequest\x1a\x1a.protocdi.MachineShowReply\"\x00\x12L\n" +
	"\fResourceList\x12\x1d.protocdi.ResourceListRequest\x1a\x1b.protocdi.ResourceListReply\"\x00\x12L\n" +
	"\fResourceShow\x12\x1d.protocdi.ResourceShowRequest\x1a\x1b.protocdi.ResourceShowReply\"\x00\x12I\n" +
	"\vCardScaling\x12\x1c.protocdi.CardScalingRequest\x1a\x1a.protocdi.CardScalingReply\"\x00B\x1fZ\x1dcdi_module/api/proto;protocdib\x06proto3"

var (
	file_api_proto_cdi_interface_proto_rawDescOnce sync.Once
	file_api_proto_cdi_interface_proto_rawDescData []byte
)

func file_api_proto_cdi_interface_proto_rawDescGZIP() []byte {
	file_api_proto_cdi_interface_proto_rawDescOnce.Do(func() {
		file_api_proto_cdi_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cdi_interface_proto_rawDesc), len(file_api_proto_cdi_interface_proto_rawDesc)))
	})
	return file_api_proto_cdi_interface_proto_rawDescData
}

var file_api_proto_cdi_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_cdi_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_cdi_interface_proto_goTypes = []any{
	(DetailCode)(0),                // 0: protocdi.DetailCode
	(*ProductInformation)(nil),     // 1: protocdi.ProductInformation
	(*CdiInformation)(nil),         // 2: protocdi.CdiInformation
	(*ResourceModifyRequests)(nil), // 3: protocdi.ResourceModifyRequests
	(*MachineCreateRequest)(nil),   // 4: protocdi.MachineCreateRequest
	(*MachineCreateReply)(nil),     // 5: protocdi.MachineCreateReply
	(*MachineDestroyRequest)(nil),  // 6: protocdi.MachineDestroyRequest
	(*MachineDestroyReply)(nil),    // 7: protocdi.MachineDestroyReply
	(*MachineShowRequest)(nil),     // 8: protocdi.MachineShowRequest
	(*MachineShowReply)(nil),       // 9: protocdi.MachineShowReply
	(*ResourceListRequest)(nil),    // 10: protocdi.ResourceListRequest
	(*ResourceListReply)(nil),      // 11: protocdi.ResourceListReply
	(*ResourceShowRequest)(nil),    // 12: protocdi.ResourceShowRequest
	(*ResourceShowReply)(nil),      // 13: protocdi.ResourceShowReply
	(*CardScalingRequest)(nil),     // 14: protocdi.CardScalingRequest
	(*CardScalingReply)(nil),       // 15: protocdi.CardScalingReply
	(proto.ResultCode)(0),          // 16: common.ResultCode
}
var file_api_proto_cdi_interface_proto_depIdxs = []int32{
	1,  // 0: protocdi.MachineCreateRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 1: protocdi.MachineCreateRequest.cdi_info:type_name -> protocdi.CdiInformation
	16, // 2: protocdi.MachineCreateReply.result:type_name -> common.ResultCode
	1,  // 3: protocdi.MachineDestroyRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 4: protocdi.MachineDestroyRequest.cdi_info:type_name -> protocdi.CdiInformation
	16, // 5: protocdi.MachineDestroyReply.result:type_name -> common.ResultCode
	1,  // 6: protocdi.MachineShowRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 7: protocdi.MachineShowRequest.cdi_info:type_name -> protocdi.CdiInformation
	16, // 8: protocdi.MachineShowReply.result:type_name -> common.ResultCode
	1,  // 9: protocdi.ResourceListRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 10: protocdi.ResourceListRequest.cdi_info:type_name -> protocdi.CdiInformation
	16, // 11: protocdi.ResourceListReply.result:type_name -> common.ResultCode
	1,  // 12: protocdi.ResourceShowRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 13: protocdi.ResourceShowRequest.cdi_info:type_name -> protocdi.CdiInformation
	16, // 14: protocdi.ResourceShowReply.result:type_name -> common.ResultCode
	1,  // 15: protocdi.CardScalingRequest.product_info:type_name -> protocdi.ProductInformation
	2,  // 16: protocdi.CardScalingRequest.cdi_info:type_name -> protocdi.CdiInformation
	3,  // 17: protocdi.CardScalingRequest.resource_modify_requests:type_name -> protocdi.ResourceModifyRequests
	16, // 18: protocdi.CardScalingReply.result:type_name -> common.ResultCode
	4,  // 19: protocdi.Cdi.MachineCreate:input_type -> protocdi.MachineCreateRequest
	6,  // 20: protocdi.Cdi.MachineDestroy:input_type -> protocdi.MachineDestroyRequest
	8,  // 21: protocdi.Cdi.MachineShow:input_type -> protocdi.MachineShowRequest
	10, // 22: protocdi.Cdi.ResourceList:input_type -> protocdi.ResourceListRequest
	12, // 23: protocdi.Cdi.ResourceShow:input_type -> protocdi.ResourceShowRequest
	14, // 24: protocdi.Cdi.CardScaling:input_type -> protocdi.CardScalingRequest
	5,  // 25: protocdi.Cdi.MachineCreate:output_type -> protocdi.MachineCreateReply
	7,  // 26: protocdi.Cdi.MachineDestroy:output_type -> protocdi.MachineDestroyReply
	9,  // 27: protocdi.Cdi.MachineShow:output_type -> protocdi.MachineShowReply
	11, // 28: protocdi.Cdi.ResourceList:output_type -> protocdi.ResourceListReply
	13, // 29: protocdi.Cdi.ResourceShow:output_type -> protocdi.ResourceShowReply
	15, // 30: protocdi.Cdi.CardScaling:output_type -> protocdi.CardScalingReply
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_cdi_interface_proto_init() }
func file_api_proto_cdi_interface_proto_init() {
	if File_api_proto_cdi_interface_proto != nil {
		return
	}
	file_api_proto_cdi_interface_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_cdi_interface_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cdi_interface_proto_rawDesc), len(file_api_proto_cdi_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cdi_interface_proto_goTypes,
		DependencyIndexes: file_api_proto_cdi_interface_proto_depIdxs,
		EnumInfos:         file_api_proto_cdi_interface_proto_enumTypes,
		MessageInfos:      file_api_proto_cdi_interface_proto_msgTypes,
	}.Build()
	File_api_proto_cdi_interface_proto = out.File
	file_api_proto_cdi_interface_proto_goTypes = nil
	file_api_proto_cdi_interface_proto_depIdxs = nil
}
