// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/cdi_interface.proto

package protocdi

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "common/api/proto"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.ResultCode(0)
)

// Validate checks the field values on ProductInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProductInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductInformationMultiError, or nil if none found.
func (m *ProductInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetVendor()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "Vendor",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetProductName()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "ProductName",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetVersion()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "Version",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Os != nil {

		if l := utf8.RuneCountInString(m.GetOs()); l < 1 || l > 128 {
			err := ProductInformationValidationError{
				field:  "Os",
				reason: "value length must be between 1 and 128 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ProductInformationMultiError(errors)
	}

	return nil
}

// ProductInformationMultiError is an error wrapping multiple validation errors
// returned by ProductInformation.ValidateAll() if the designated constraints
// aren't met.
type ProductInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductInformationMultiError) AllErrors() []error { return m }

// ProductInformationValidationError is the validation error returned by
// ProductInformation.Validate if the designated constraints aren't met.
type ProductInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductInformationValidationError) ErrorName() string {
	return "ProductInformationValidationError"
}

// Error satisfies the builtin error interface
func (e ProductInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductInformationValidationError{}

// Validate checks the field values on CdiInformation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CdiInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CdiInformation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CdiInformationMultiError,
// or nil if none found.
func (m *CdiInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *CdiInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRemoteHost()); l < 1 || l > 128 {
		err := CdiInformationValidationError{
			field:  "RemoteHost",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRemoteUser()); l < 1 || l > 32 {
		err := CdiInformationValidationError{
			field:  "RemoteUser",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CdiInformationMultiError(errors)
	}

	return nil
}

// CdiInformationMultiError is an error wrapping multiple validation errors
// returned by CdiInformation.ValidateAll() if the designated constraints
// aren't met.
type CdiInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CdiInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CdiInformationMultiError) AllErrors() []error { return m }

// CdiInformationValidationError is the validation error returned by
// CdiInformation.Validate if the designated constraints aren't met.
type CdiInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CdiInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CdiInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CdiInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CdiInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CdiInformationValidationError) ErrorName() string { return "CdiInformationValidationError" }

// Error satisfies the builtin error interface
func (e CdiInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCdiInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CdiInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CdiInformationValidationError{}

// Validate checks the field values on ResourceModifyRequests with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceModifyRequests) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceModifyRequests with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceModifyRequestsMultiError, or nil if none found.
func (m *ResourceModifyRequests) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceModifyRequests) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetOp()); l < 1 || l > 6 {
		err := ResourceModifyRequestsValidationError{
			field:  "Op",
			reason: "value length must be between 1 and 6 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetResourceName()); l < 1 || l > 32 {
		err := ResourceModifyRequestsValidationError{
			field:  "ResourceName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ResourceModifyRequestsMultiError(errors)
	}

	return nil
}

// ResourceModifyRequestsMultiError is an error wrapping multiple validation
// errors returned by ResourceModifyRequests.ValidateAll() if the designated
// constraints aren't met.
type ResourceModifyRequestsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceModifyRequestsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceModifyRequestsMultiError) AllErrors() []error { return m }

// ResourceModifyRequestsValidationError is the validation error returned by
// ResourceModifyRequests.Validate if the designated constraints aren't met.
type ResourceModifyRequestsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceModifyRequestsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceModifyRequestsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceModifyRequestsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceModifyRequestsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceModifyRequestsValidationError) ErrorName() string {
	return "ResourceModifyRequestsValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceModifyRequestsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceModifyRequests.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceModifyRequestsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceModifyRequestsValidationError{}

// Validate checks the field values on MachineCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MachineCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineCreateRequestMultiError, or nil if none found.
func (m *MachineCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := MachineCreateRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineCreateRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineCreateRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineCreateRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := MachineCreateRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineCreateRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineCreateRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineCreateRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetGroupName()); l < 1 || l > 32 {
		err := MachineCreateRequestValidationError{
			field:  "GroupName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMachineName()); l < 1 || l > 22 {
		err := MachineCreateRequestValidationError{
			field:  "MachineName",
			reason: "value length must be between 1 and 22 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetResourceList()) < 1 {
		err := MachineCreateRequestValidationError{
			field:  "ResourceList",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetResourceList() {
		_, _ = idx, item

		if l := utf8.RuneCountInString(item); l < 1 || l > 128 {
			err := MachineCreateRequestValidationError{
				field:  fmt.Sprintf("ResourceList[%v]", idx),
				reason: "value length must be between 1 and 128 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return MachineCreateRequestMultiError(errors)
	}

	return nil
}

// MachineCreateRequestMultiError is an error wrapping multiple validation
// errors returned by MachineCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type MachineCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineCreateRequestMultiError) AllErrors() []error { return m }

// MachineCreateRequestValidationError is the validation error returned by
// MachineCreateRequest.Validate if the designated constraints aren't met.
type MachineCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineCreateRequestValidationError) ErrorName() string {
	return "MachineCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MachineCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineCreateRequestValidationError{}

// Validate checks the field values on MachineCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MachineCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineCreateReplyMultiError, or nil if none found.
func (m *MachineCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return MachineCreateReplyMultiError(errors)
	}

	return nil
}

// MachineCreateReplyMultiError is an error wrapping multiple validation errors
// returned by MachineCreateReply.ValidateAll() if the designated constraints
// aren't met.
type MachineCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineCreateReplyMultiError) AllErrors() []error { return m }

// MachineCreateReplyValidationError is the validation error returned by
// MachineCreateReply.Validate if the designated constraints aren't met.
type MachineCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineCreateReplyValidationError) ErrorName() string {
	return "MachineCreateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e MachineCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineCreateReplyValidationError{}

// Validate checks the field values on MachineDestroyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MachineDestroyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineDestroyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineDestroyRequestMultiError, or nil if none found.
func (m *MachineDestroyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineDestroyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := MachineDestroyRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineDestroyRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineDestroyRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineDestroyRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := MachineDestroyRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineDestroyRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineDestroyRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineDestroyRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetGroupName()); l < 1 || l > 32 {
		err := MachineDestroyRequestValidationError{
			field:  "GroupName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMachineName()); l < 1 || l > 22 {
		err := MachineDestroyRequestValidationError{
			field:  "MachineName",
			reason: "value length must be between 1 and 22 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return MachineDestroyRequestMultiError(errors)
	}

	return nil
}

// MachineDestroyRequestMultiError is an error wrapping multiple validation
// errors returned by MachineDestroyRequest.ValidateAll() if the designated
// constraints aren't met.
type MachineDestroyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineDestroyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineDestroyRequestMultiError) AllErrors() []error { return m }

// MachineDestroyRequestValidationError is the validation error returned by
// MachineDestroyRequest.Validate if the designated constraints aren't met.
type MachineDestroyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineDestroyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineDestroyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineDestroyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineDestroyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineDestroyRequestValidationError) ErrorName() string {
	return "MachineDestroyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MachineDestroyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineDestroyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineDestroyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineDestroyRequestValidationError{}

// Validate checks the field values on MachineDestroyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MachineDestroyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineDestroyReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineDestroyReplyMultiError, or nil if none found.
func (m *MachineDestroyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineDestroyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return MachineDestroyReplyMultiError(errors)
	}

	return nil
}

// MachineDestroyReplyMultiError is an error wrapping multiple validation
// errors returned by MachineDestroyReply.ValidateAll() if the designated
// constraints aren't met.
type MachineDestroyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineDestroyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineDestroyReplyMultiError) AllErrors() []error { return m }

// MachineDestroyReplyValidationError is the validation error returned by
// MachineDestroyReply.Validate if the designated constraints aren't met.
type MachineDestroyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineDestroyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineDestroyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineDestroyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineDestroyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineDestroyReplyValidationError) ErrorName() string {
	return "MachineDestroyReplyValidationError"
}

// Error satisfies the builtin error interface
func (e MachineDestroyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineDestroyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineDestroyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineDestroyReplyValidationError{}

// Validate checks the field values on MachineShowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MachineShowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineShowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineShowRequestMultiError, or nil if none found.
func (m *MachineShowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineShowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := MachineShowRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineShowRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineShowRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineShowRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := MachineShowRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MachineShowRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MachineShowRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MachineShowRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetGroupName()); l < 1 || l > 32 {
		err := MachineShowRequestValidationError{
			field:  "GroupName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMachineName()); l < 1 || l > 22 {
		err := MachineShowRequestValidationError{
			field:  "MachineName",
			reason: "value length must be between 1 and 22 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return MachineShowRequestMultiError(errors)
	}

	return nil
}

// MachineShowRequestMultiError is an error wrapping multiple validation errors
// returned by MachineShowRequest.ValidateAll() if the designated constraints
// aren't met.
type MachineShowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineShowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineShowRequestMultiError) AllErrors() []error { return m }

// MachineShowRequestValidationError is the validation error returned by
// MachineShowRequest.Validate if the designated constraints aren't met.
type MachineShowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineShowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineShowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineShowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineShowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineShowRequestValidationError) ErrorName() string {
	return "MachineShowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MachineShowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineShowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineShowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineShowRequestValidationError{}

// Validate checks the field values on MachineShowReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MachineShowReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MachineShowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MachineShowReplyMultiError, or nil if none found.
func (m *MachineShowReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MachineShowReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	// no validation rules for Data

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return MachineShowReplyMultiError(errors)
	}

	return nil
}

// MachineShowReplyMultiError is an error wrapping multiple validation errors
// returned by MachineShowReply.ValidateAll() if the designated constraints
// aren't met.
type MachineShowReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MachineShowReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MachineShowReplyMultiError) AllErrors() []error { return m }

// MachineShowReplyValidationError is the validation error returned by
// MachineShowReply.Validate if the designated constraints aren't met.
type MachineShowReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MachineShowReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MachineShowReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MachineShowReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MachineShowReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MachineShowReplyValidationError) ErrorName() string { return "MachineShowReplyValidationError" }

// Error satisfies the builtin error interface
func (e MachineShowReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMachineShowReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MachineShowReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MachineShowReplyValidationError{}

// Validate checks the field values on ResourceListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceListRequestMultiError, or nil if none found.
func (m *ResourceListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := ResourceListRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceListRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceListRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceListRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := ResourceListRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceListRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceListRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceListRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetGroupName()); l < 1 || l > 32 {
		err := ResourceListRequestValidationError{
			field:  "GroupName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return ResourceListRequestMultiError(errors)
	}

	return nil
}

// ResourceListRequestMultiError is an error wrapping multiple validation
// errors returned by ResourceListRequest.ValidateAll() if the designated
// constraints aren't met.
type ResourceListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceListRequestMultiError) AllErrors() []error { return m }

// ResourceListRequestValidationError is the validation error returned by
// ResourceListRequest.Validate if the designated constraints aren't met.
type ResourceListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceListRequestValidationError) ErrorName() string {
	return "ResourceListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceListRequestValidationError{}

// Validate checks the field values on ResourceListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResourceListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceListReplyMultiError, or nil if none found.
func (m *ResourceListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	// no validation rules for Data

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return ResourceListReplyMultiError(errors)
	}

	return nil
}

// ResourceListReplyMultiError is an error wrapping multiple validation errors
// returned by ResourceListReply.ValidateAll() if the designated constraints
// aren't met.
type ResourceListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceListReplyMultiError) AllErrors() []error { return m }

// ResourceListReplyValidationError is the validation error returned by
// ResourceListReply.Validate if the designated constraints aren't met.
type ResourceListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceListReplyValidationError) ErrorName() string {
	return "ResourceListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceListReplyValidationError{}

// Validate checks the field values on ResourceShowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceShowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceShowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceShowRequestMultiError, or nil if none found.
func (m *ResourceShowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceShowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := ResourceShowRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceShowRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceShowRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceShowRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := ResourceShowRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceShowRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceShowRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceShowRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetResourceName()); l < 1 || l > 32 {
		err := ResourceShowRequestValidationError{
			field:  "ResourceName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return ResourceShowRequestMultiError(errors)
	}

	return nil
}

// ResourceShowRequestMultiError is an error wrapping multiple validation
// errors returned by ResourceShowRequest.ValidateAll() if the designated
// constraints aren't met.
type ResourceShowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceShowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceShowRequestMultiError) AllErrors() []error { return m }

// ResourceShowRequestValidationError is the validation error returned by
// ResourceShowRequest.Validate if the designated constraints aren't met.
type ResourceShowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceShowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceShowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceShowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceShowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceShowRequestValidationError) ErrorName() string {
	return "ResourceShowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceShowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceShowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceShowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceShowRequestValidationError{}

// Validate checks the field values on ResourceShowReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResourceShowReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceShowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceShowReplyMultiError, or nil if none found.
func (m *ResourceShowReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceShowReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	// no validation rules for Data

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return ResourceShowReplyMultiError(errors)
	}

	return nil
}

// ResourceShowReplyMultiError is an error wrapping multiple validation errors
// returned by ResourceShowReply.ValidateAll() if the designated constraints
// aren't met.
type ResourceShowReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceShowReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceShowReplyMultiError) AllErrors() []error { return m }

// ResourceShowReplyValidationError is the validation error returned by
// ResourceShowReply.Validate if the designated constraints aren't met.
type ResourceShowReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceShowReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceShowReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceShowReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceShowReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceShowReplyValidationError) ErrorName() string {
	return "ResourceShowReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceShowReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceShowReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceShowReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceShowReplyValidationError{}

// Validate checks the field values on CardScalingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CardScalingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CardScalingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CardScalingRequestMultiError, or nil if none found.
func (m *CardScalingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CardScalingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := CardScalingRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CardScalingRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CardScalingRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CardScalingRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCdiInfo() == nil {
		err := CardScalingRequestValidationError{
			field:  "CdiInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCdiInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CardScalingRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CardScalingRequestValidationError{
					field:  "CdiInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCdiInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CardScalingRequestValidationError{
				field:  "CdiInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetGroupName()); l < 1 || l > 32 {
		err := CardScalingRequestValidationError{
			field:  "GroupName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMachineName()); l < 1 || l > 22 {
		err := CardScalingRequestValidationError{
			field:  "MachineName",
			reason: "value length must be between 1 and 22 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetResourceModifyRequests()) < 1 {
		err := CardScalingRequestValidationError{
			field:  "ResourceModifyRequests",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetResourceModifyRequests() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CardScalingRequestValidationError{
						field:  fmt.Sprintf("ResourceModifyRequests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CardScalingRequestValidationError{
						field:  fmt.Sprintf("ResourceModifyRequests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CardScalingRequestValidationError{
					field:  fmt.Sprintf("ResourceModifyRequests[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return CardScalingRequestMultiError(errors)
	}

	return nil
}

// CardScalingRequestMultiError is an error wrapping multiple validation errors
// returned by CardScalingRequest.ValidateAll() if the designated constraints
// aren't met.
type CardScalingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CardScalingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CardScalingRequestMultiError) AllErrors() []error { return m }

// CardScalingRequestValidationError is the validation error returned by
// CardScalingRequest.Validate if the designated constraints aren't met.
type CardScalingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CardScalingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CardScalingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CardScalingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CardScalingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CardScalingRequestValidationError) ErrorName() string {
	return "CardScalingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CardScalingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCardScalingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CardScalingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CardScalingRequestValidationError{}

// Validate checks the field values on CardScalingReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CardScalingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CardScalingReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CardScalingReplyMultiError, or nil if none found.
func (m *CardScalingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CardScalingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return CardScalingReplyMultiError(errors)
	}

	return nil
}

// CardScalingReplyMultiError is an error wrapping multiple validation errors
// returned by CardScalingReply.ValidateAll() if the designated constraints
// aren't met.
type CardScalingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CardScalingReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CardScalingReplyMultiError) AllErrors() []error { return m }

// CardScalingReplyValidationError is the validation error returned by
// CardScalingReply.Validate if the designated constraints aren't met.
type CardScalingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CardScalingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CardScalingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CardScalingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CardScalingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CardScalingReplyValidationError) ErrorName() string { return "CardScalingReplyValidationError" }

// Error satisfies the builtin error interface
func (e CardScalingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCardScalingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CardScalingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CardScalingReplyValidationError{}
