// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/cdi_interface.proto

package protocdi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cdi_MachineCreate_FullMethodName  = "/protocdi.Cdi/MachineCreate"
	Cdi_MachineDestroy_FullMethodName = "/protocdi.Cdi/MachineDestroy"
	Cdi_MachineShow_FullMethodName    = "/protocdi.Cdi/MachineShow"
	Cdi_ResourceList_FullMethodName   = "/protocdi.Cdi/ResourceList"
	Cdi_ResourceShow_FullMethodName   = "/protocdi.Cdi/ResourceShow"
	Cdi_CardScaling_FullMethodName    = "/protocdi.Cdi/CardScaling"
)

// CdiClient is the client API for Cdi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define service for CDI
type CdiClient interface {
	MachineCreate(ctx context.Context, in *MachineCreateRequest, opts ...grpc.CallOption) (*MachineCreateReply, error)
	MachineDestroy(ctx context.Context, in *MachineDestroyRequest, opts ...grpc.CallOption) (*MachineDestroyReply, error)
	MachineShow(ctx context.Context, in *MachineShowRequest, opts ...grpc.CallOption) (*MachineShowReply, error)
	ResourceList(ctx context.Context, in *ResourceListRequest, opts ...grpc.CallOption) (*ResourceListReply, error)
	ResourceShow(ctx context.Context, in *ResourceShowRequest, opts ...grpc.CallOption) (*ResourceShowReply, error)
	CardScaling(ctx context.Context, in *CardScalingRequest, opts ...grpc.CallOption) (*CardScalingReply, error)
}

type cdiClient struct {
	cc grpc.ClientConnInterface
}

func NewCdiClient(cc grpc.ClientConnInterface) CdiClient {
	return &cdiClient{cc}
}

func (c *cdiClient) MachineCreate(ctx context.Context, in *MachineCreateRequest, opts ...grpc.CallOption) (*MachineCreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineCreateReply)
	err := c.cc.Invoke(ctx, Cdi_MachineCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdiClient) MachineDestroy(ctx context.Context, in *MachineDestroyRequest, opts ...grpc.CallOption) (*MachineDestroyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineDestroyReply)
	err := c.cc.Invoke(ctx, Cdi_MachineDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdiClient) MachineShow(ctx context.Context, in *MachineShowRequest, opts ...grpc.CallOption) (*MachineShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineShowReply)
	err := c.cc.Invoke(ctx, Cdi_MachineShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdiClient) ResourceList(ctx context.Context, in *ResourceListRequest, opts ...grpc.CallOption) (*ResourceListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceListReply)
	err := c.cc.Invoke(ctx, Cdi_ResourceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdiClient) ResourceShow(ctx context.Context, in *ResourceShowRequest, opts ...grpc.CallOption) (*ResourceShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceShowReply)
	err := c.cc.Invoke(ctx, Cdi_ResourceShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdiClient) CardScaling(ctx context.Context, in *CardScalingRequest, opts ...grpc.CallOption) (*CardScalingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardScalingReply)
	err := c.cc.Invoke(ctx, Cdi_CardScaling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdiServer is the server API for Cdi service.
// All implementations must embed UnimplementedCdiServer
// for forward compatibility.
//
// Define service for CDI
type CdiServer interface {
	MachineCreate(context.Context, *MachineCreateRequest) (*MachineCreateReply, error)
	MachineDestroy(context.Context, *MachineDestroyRequest) (*MachineDestroyReply, error)
	MachineShow(context.Context, *MachineShowRequest) (*MachineShowReply, error)
	ResourceList(context.Context, *ResourceListRequest) (*ResourceListReply, error)
	ResourceShow(context.Context, *ResourceShowRequest) (*ResourceShowReply, error)
	CardScaling(context.Context, *CardScalingRequest) (*CardScalingReply, error)
	mustEmbedUnimplementedCdiServer()
}

// UnimplementedCdiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCdiServer struct{}

func (UnimplementedCdiServer) MachineCreate(context.Context, *MachineCreateRequest) (*MachineCreateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineCreate not implemented")
}
func (UnimplementedCdiServer) MachineDestroy(context.Context, *MachineDestroyRequest) (*MachineDestroyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineDestroy not implemented")
}
func (UnimplementedCdiServer) MachineShow(context.Context, *MachineShowRequest) (*MachineShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineShow not implemented")
}
func (UnimplementedCdiServer) ResourceList(context.Context, *ResourceListRequest) (*ResourceListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceList not implemented")
}
func (UnimplementedCdiServer) ResourceShow(context.Context, *ResourceShowRequest) (*ResourceShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceShow not implemented")
}
func (UnimplementedCdiServer) CardScaling(context.Context, *CardScalingRequest) (*CardScalingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CardScaling not implemented")
}
func (UnimplementedCdiServer) mustEmbedUnimplementedCdiServer() {}
func (UnimplementedCdiServer) testEmbeddedByValue()             {}

// UnsafeCdiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdiServer will
// result in compilation errors.
type UnsafeCdiServer interface {
	mustEmbedUnimplementedCdiServer()
}

func RegisterCdiServer(s grpc.ServiceRegistrar, srv CdiServer) {
	// If the following call panics, it indicates UnimplementedCdiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cdi_ServiceDesc, srv)
}

func _Cdi_MachineCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).MachineCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_MachineCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).MachineCreate(ctx, req.(*MachineCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdi_MachineDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).MachineDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_MachineDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).MachineDestroy(ctx, req.(*MachineDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdi_MachineShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).MachineShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_MachineShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).MachineShow(ctx, req.(*MachineShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdi_ResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).ResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_ResourceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).ResourceList(ctx, req.(*ResourceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdi_ResourceShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).ResourceShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_ResourceShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).ResourceShow(ctx, req.(*ResourceShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdi_CardScaling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardScalingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdiServer).CardScaling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cdi_CardScaling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdiServer).CardScaling(ctx, req.(*CardScalingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cdi_ServiceDesc is the grpc.ServiceDesc for Cdi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cdi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocdi.Cdi",
	HandlerType: (*CdiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MachineCreate",
			Handler:    _Cdi_MachineCreate_Handler,
		},
		{
			MethodName: "MachineDestroy",
			Handler:    _Cdi_MachineDestroy_Handler,
		},
		{
			MethodName: "MachineShow",
			Handler:    _Cdi_MachineShow_Handler,
		},
		{
			MethodName: "ResourceList",
			Handler:    _Cdi_ResourceList_Handler,
		},
		{
			MethodName: "ResourceShow",
			Handler:    _Cdi_ResourceShow_Handler,
		},
		{
			MethodName: "CardScaling",
			Handler:    _Cdi_CardScaling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cdi_interface.proto",
}
