// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/maas_interface.proto

package protomaas

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maas_MachineRegister_FullMethodName = "/protomaas.Maas/MachineRegister"
	Maas_MachineDelete_FullMethodName   = "/protomaas.Maas/MachineDelete"
	Maas_OsDeploy_FullMethodName        = "/protomaas.Maas/OsDeploy"
	Maas_OsRelease_FullMethodName       = "/protomaas.Maas/OsRelease"
	Maas_VmCompose_FullMethodName       = "/protomaas.Maas/VmCompose"
	Maas_VmDelete_FullMethodName        = "/protomaas.Maas/VmDelete"
	Maas_MachineList_FullMethodName     = "/protomaas.Maas/MachineList"
	Maas_MachineShow_FullMethodName     = "/protomaas.Maas/MachineShow"
	Maas_Cancel_FullMethodName          = "/protomaas.Maas/Cancel"
	Maas_NetworkUpdate_FullMethodName   = "/protomaas.Maas/NetworkUpdate"
	Maas_PowerOn_FullMethodName         = "/protomaas.Maas/PowerOn"
	Maas_PowerOff_FullMethodName        = "/protomaas.Maas/PowerOff"
	Maas_KubeadmReset_FullMethodName    = "/protomaas.Maas/KubeadmReset"
	Maas_KubeadmJoin_FullMethodName     = "/protomaas.Maas/KubeadmJoin"
)

// MaasClient is the client API for Maas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define service for MaaS
type MaasClient interface {
	MachineRegister(ctx context.Context, in *MachineRegisterRequest, opts ...grpc.CallOption) (*MachineRegisterResponse, error)
	MachineDelete(ctx context.Context, in *MachineDeleteRequest, opts ...grpc.CallOption) (*MachineDeleteResponse, error)
	OsDeploy(ctx context.Context, in *OsDeployRequest, opts ...grpc.CallOption) (*OsDeployResponse, error)
	OsRelease(ctx context.Context, in *OsReleaseRequest, opts ...grpc.CallOption) (*OsReleaseResponse, error)
	VmCompose(ctx context.Context, in *VmComposeRequest, opts ...grpc.CallOption) (*VmComposeResponse, error)
	VmDelete(ctx context.Context, in *VmDeleteRequest, opts ...grpc.CallOption) (*VmDeleteResponse, error)
	MachineList(ctx context.Context, in *MachineListRequest, opts ...grpc.CallOption) (*MachineListResponse, error)
	MachineShow(ctx context.Context, in *MachineShowRequest, opts ...grpc.CallOption) (*MachineShowResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	NetworkUpdate(ctx context.Context, in *NetworkUpdateRequest, opts ...grpc.CallOption) (*NetworkUpdateResponse, error)
	PowerOn(ctx context.Context, in *PowerOnRequest, opts ...grpc.CallOption) (*PowerOnResponse, error)
	PowerOff(ctx context.Context, in *PowerOffRequest, opts ...grpc.CallOption) (*PowerOffResponse, error)
	KubeadmReset(ctx context.Context, in *KubeadmResetRequest, opts ...grpc.CallOption) (*KubeadmResetResponse, error)
	KubeadmJoin(ctx context.Context, in *KubeadmJoinRequest, opts ...grpc.CallOption) (*KubeadmJoinResponse, error)
}

type maasClient struct {
	cc grpc.ClientConnInterface
}

func NewMaasClient(cc grpc.ClientConnInterface) MaasClient {
	return &maasClient{cc}
}

func (c *maasClient) MachineRegister(ctx context.Context, in *MachineRegisterRequest, opts ...grpc.CallOption) (*MachineRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineRegisterResponse)
	err := c.cc.Invoke(ctx, Maas_MachineRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) MachineDelete(ctx context.Context, in *MachineDeleteRequest, opts ...grpc.CallOption) (*MachineDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineDeleteResponse)
	err := c.cc.Invoke(ctx, Maas_MachineDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) OsDeploy(ctx context.Context, in *OsDeployRequest, opts ...grpc.CallOption) (*OsDeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OsDeployResponse)
	err := c.cc.Invoke(ctx, Maas_OsDeploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) OsRelease(ctx context.Context, in *OsReleaseRequest, opts ...grpc.CallOption) (*OsReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OsReleaseResponse)
	err := c.cc.Invoke(ctx, Maas_OsRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) VmCompose(ctx context.Context, in *VmComposeRequest, opts ...grpc.CallOption) (*VmComposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmComposeResponse)
	err := c.cc.Invoke(ctx, Maas_VmCompose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) VmDelete(ctx context.Context, in *VmDeleteRequest, opts ...grpc.CallOption) (*VmDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmDeleteResponse)
	err := c.cc.Invoke(ctx, Maas_VmDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) MachineList(ctx context.Context, in *MachineListRequest, opts ...grpc.CallOption) (*MachineListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineListResponse)
	err := c.cc.Invoke(ctx, Maas_MachineList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) MachineShow(ctx context.Context, in *MachineShowRequest, opts ...grpc.CallOption) (*MachineShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineShowResponse)
	err := c.cc.Invoke(ctx, Maas_MachineShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Maas_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) NetworkUpdate(ctx context.Context, in *NetworkUpdateRequest, opts ...grpc.CallOption) (*NetworkUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkUpdateResponse)
	err := c.cc.Invoke(ctx, Maas_NetworkUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) PowerOn(ctx context.Context, in *PowerOnRequest, opts ...grpc.CallOption) (*PowerOnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerOnResponse)
	err := c.cc.Invoke(ctx, Maas_PowerOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) PowerOff(ctx context.Context, in *PowerOffRequest, opts ...grpc.CallOption) (*PowerOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerOffResponse)
	err := c.cc.Invoke(ctx, Maas_PowerOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) KubeadmReset(ctx context.Context, in *KubeadmResetRequest, opts ...grpc.CallOption) (*KubeadmResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeadmResetResponse)
	err := c.cc.Invoke(ctx, Maas_KubeadmReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maasClient) KubeadmJoin(ctx context.Context, in *KubeadmJoinRequest, opts ...grpc.CallOption) (*KubeadmJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeadmJoinResponse)
	err := c.cc.Invoke(ctx, Maas_KubeadmJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaasServer is the server API for Maas service.
// All implementations must embed UnimplementedMaasServer
// for forward compatibility.
//
// Define service for MaaS
type MaasServer interface {
	MachineRegister(context.Context, *MachineRegisterRequest) (*MachineRegisterResponse, error)
	MachineDelete(context.Context, *MachineDeleteRequest) (*MachineDeleteResponse, error)
	OsDeploy(context.Context, *OsDeployRequest) (*OsDeployResponse, error)
	OsRelease(context.Context, *OsReleaseRequest) (*OsReleaseResponse, error)
	VmCompose(context.Context, *VmComposeRequest) (*VmComposeResponse, error)
	VmDelete(context.Context, *VmDeleteRequest) (*VmDeleteResponse, error)
	MachineList(context.Context, *MachineListRequest) (*MachineListResponse, error)
	MachineShow(context.Context, *MachineShowRequest) (*MachineShowResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	NetworkUpdate(context.Context, *NetworkUpdateRequest) (*NetworkUpdateResponse, error)
	PowerOn(context.Context, *PowerOnRequest) (*PowerOnResponse, error)
	PowerOff(context.Context, *PowerOffRequest) (*PowerOffResponse, error)
	KubeadmReset(context.Context, *KubeadmResetRequest) (*KubeadmResetResponse, error)
	KubeadmJoin(context.Context, *KubeadmJoinRequest) (*KubeadmJoinResponse, error)
	mustEmbedUnimplementedMaasServer()
}

// UnimplementedMaasServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaasServer struct{}

func (UnimplementedMaasServer) MachineRegister(context.Context, *MachineRegisterRequest) (*MachineRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineRegister not implemented")
}
func (UnimplementedMaasServer) MachineDelete(context.Context, *MachineDeleteRequest) (*MachineDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineDelete not implemented")
}
func (UnimplementedMaasServer) OsDeploy(context.Context, *OsDeployRequest) (*OsDeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OsDeploy not implemented")
}
func (UnimplementedMaasServer) OsRelease(context.Context, *OsReleaseRequest) (*OsReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OsRelease not implemented")
}
func (UnimplementedMaasServer) VmCompose(context.Context, *VmComposeRequest) (*VmComposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VmCompose not implemented")
}
func (UnimplementedMaasServer) VmDelete(context.Context, *VmDeleteRequest) (*VmDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VmDelete not implemented")
}
func (UnimplementedMaasServer) MachineList(context.Context, *MachineListRequest) (*MachineListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineList not implemented")
}
func (UnimplementedMaasServer) MachineShow(context.Context, *MachineShowRequest) (*MachineShowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineShow not implemented")
}
func (UnimplementedMaasServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedMaasServer) NetworkUpdate(context.Context, *NetworkUpdateRequest) (*NetworkUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NetworkUpdate not implemented")
}
func (UnimplementedMaasServer) PowerOn(context.Context, *PowerOnRequest) (*PowerOnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PowerOn not implemented")
}
func (UnimplementedMaasServer) PowerOff(context.Context, *PowerOffRequest) (*PowerOffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PowerOff not implemented")
}
func (UnimplementedMaasServer) KubeadmReset(context.Context, *KubeadmResetRequest) (*KubeadmResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KubeadmReset not implemented")
}
func (UnimplementedMaasServer) KubeadmJoin(context.Context, *KubeadmJoinRequest) (*KubeadmJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KubeadmJoin not implemented")
}
func (UnimplementedMaasServer) mustEmbedUnimplementedMaasServer() {}
func (UnimplementedMaasServer) testEmbeddedByValue()              {}

// UnsafeMaasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaasServer will
// result in compilation errors.
type UnsafeMaasServer interface {
	mustEmbedUnimplementedMaasServer()
}

func RegisterMaasServer(s grpc.ServiceRegistrar, srv MaasServer) {
	// If the following call panics, it indicates UnimplementedMaasServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maas_ServiceDesc, srv)
}

func _Maas_MachineRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).MachineRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_MachineRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).MachineRegister(ctx, req.(*MachineRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_MachineDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).MachineDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_MachineDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).MachineDelete(ctx, req.(*MachineDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_OsDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OsDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).OsDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_OsDeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).OsDeploy(ctx, req.(*OsDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_OsRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OsReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).OsRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_OsRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).OsRelease(ctx, req.(*OsReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_VmCompose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmComposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).VmCompose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_VmCompose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).VmCompose(ctx, req.(*VmComposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_VmDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).VmDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_VmDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).VmDelete(ctx, req.(*VmDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_MachineList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).MachineList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_MachineList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).MachineList(ctx, req.(*MachineListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_MachineShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).MachineShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_MachineShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).MachineShow(ctx, req.(*MachineShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_NetworkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).NetworkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_NetworkUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).NetworkUpdate(ctx, req.(*NetworkUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_PowerOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).PowerOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_PowerOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).PowerOn(ctx, req.(*PowerOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_PowerOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).PowerOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_PowerOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).PowerOff(ctx, req.(*PowerOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_KubeadmReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeadmResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).KubeadmReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_KubeadmReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).KubeadmReset(ctx, req.(*KubeadmResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maas_KubeadmJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeadmJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaasServer).KubeadmJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maas_KubeadmJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaasServer).KubeadmJoin(ctx, req.(*KubeadmJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maas_ServiceDesc is the grpc.ServiceDesc for Maas service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maas_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protomaas.Maas",
	HandlerType: (*MaasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MachineRegister",
			Handler:    _Maas_MachineRegister_Handler,
		},
		{
			MethodName: "MachineDelete",
			Handler:    _Maas_MachineDelete_Handler,
		},
		{
			MethodName: "OsDeploy",
			Handler:    _Maas_OsDeploy_Handler,
		},
		{
			MethodName: "OsRelease",
			Handler:    _Maas_OsRelease_Handler,
		},
		{
			MethodName: "VmCompose",
			Handler:    _Maas_VmCompose_Handler,
		},
		{
			MethodName: "VmDelete",
			Handler:    _Maas_VmDelete_Handler,
		},
		{
			MethodName: "MachineList",
			Handler:    _Maas_MachineList_Handler,
		},
		{
			MethodName: "MachineShow",
			Handler:    _Maas_MachineShow_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Maas_Cancel_Handler,
		},
		{
			MethodName: "NetworkUpdate",
			Handler:    _Maas_NetworkUpdate_Handler,
		},
		{
			MethodName: "PowerOn",
			Handler:    _Maas_PowerOn_Handler,
		},
		{
			MethodName: "PowerOff",
			Handler:    _Maas_PowerOff_Handler,
		},
		{
			MethodName: "KubeadmReset",
			Handler:    _Maas_KubeadmReset_Handler,
		},
		{
			MethodName: "KubeadmJoin",
			Handler:    _Maas_KubeadmJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/maas_interface.proto",
}
