// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/maas_interface.proto

package protomaas

import (
	proto "common/api/proto"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for detail error code
type DetailCode int32

const (
	DetailCode_ZERO                   DetailCode = 0
	DetailCode_IF_PARAMETER_INVALID   DetailCode = 41
	DetailCode_UNSUPPORT_PRODUCT      DetailCode = 42
	DetailCode_IF_SEQUENCE_ERROR      DetailCode = 52
	DetailCode_IF_CANCEL_UNAVAILABLE  DetailCode = 53
	DetailCode_MAAS_ENVIRONMENT_ERROR DetailCode = 61
	DetailCode_MAAS_RESPONSE_INVALID  DetailCode = 81
)

// Enum value maps for DetailCode.
var (
	DetailCode_name = map[int32]string{
		0:  "ZERO",
		41: "IF_PARAMETER_INVALID",
		42: "UNSUPPORT_PRODUCT",
		52: "IF_SEQUENCE_ERROR",
		53: "IF_CANCEL_UNAVAILABLE",
		61: "MAAS_ENVIRONMENT_ERROR",
		81: "MAAS_RESPONSE_INVALID",
	}
	DetailCode_value = map[string]int32{
		"ZERO":                   0,
		"IF_PARAMETER_INVALID":   41,
		"UNSUPPORT_PRODUCT":      42,
		"IF_SEQUENCE_ERROR":      52,
		"IF_CANCEL_UNAVAILABLE":  53,
		"MAAS_ENVIRONMENT_ERROR": 61,
		"MAAS_RESPONSE_INVALID":  81,
	}
)

func (x DetailCode) Enum() *DetailCode {
	p := new(DetailCode)
	*p = x
	return p
}

func (x DetailCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetailCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_maas_interface_proto_enumTypes[0].Descriptor()
}

func (DetailCode) Type() protoreflect.EnumType {
	return &file_api_proto_maas_interface_proto_enumTypes[0]
}

func (x DetailCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetailCode.Descriptor instead.
func (DetailCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{0}
}

// message of Product information
type ProductInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`                              // vendor name
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // product name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // version
	Os            *string                `protobuf:"bytes,4,opt,name=os,proto3,oneof" json:"os,omitempty"`                                // os info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInformation) Reset() {
	*x = ProductInformation{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInformation) ProtoMessage() {}

func (x *ProductInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInformation.ProtoReflect.Descriptor instead.
func (*ProductInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInformation) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ProductInformation) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProductInformation) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

// message of MAAS information
type MaasInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessUrl     string                 `protobuf:"bytes,1,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"` // access URL for MaaS server
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`          // API-KEY for MaaS server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaasInformation) Reset() {
	*x = MaasInformation{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaasInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaasInformation) ProtoMessage() {}

func (x *MaasInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaasInformation.ProtoReflect.Descriptor instead.
func (*MaasInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{1}
}

func (x *MaasInformation) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

func (x *MaasInformation) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Network information
type NetworkInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`             // MAC address for target NIC (format: XX:XX:XX:XX:XX:XX)
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`                                           // CIDR for specified machine (format: x.x.x.x/y)
	AddressStart  *string                `protobuf:"bytes,3,opt,name=address_start,json=addressStart,proto3,oneof" json:"address_start,omitempty"` // Min. IP range in specified cidr (format: x.x.x.x)
	AddressEnd    *string                `protobuf:"bytes,4,opt,name=address_end,json=addressEnd,proto3,oneof" json:"address_end,omitempty"`       // Max. IP range in specified cidr (format: x.x.x.x)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInformation) Reset() {
	*x = NetworkInformation{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInformation) ProtoMessage() {}

func (x *NetworkInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInformation.ProtoReflect.Descriptor instead.
func (*NetworkInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkInformation) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInformation) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkInformation) GetAddressStart() string {
	if x != nil && x.AddressStart != nil {
		return *x.AddressStart
	}
	return ""
}

func (x *NetworkInformation) GetAddressEnd() string {
	if x != nil && x.AddressEnd != nil {
		return *x.AddressEnd
	}
	return ""
}

// OS information
type OsInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distribution  string                 `protobuf:"bytes,1,opt,name=distribution,proto3" json:"distribution,omitempty"` // OS distribution
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`           // OS version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsInformation) Reset() {
	*x = OsInformation{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsInformation) ProtoMessage() {}

func (x *OsInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsInformation.ProtoReflect.Descriptor instead.
func (*OsInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{3}
}

func (x *OsInformation) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *OsInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Network information for CNI
type NetworkInformationCni struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IfName        string                 `protobuf:"bytes,1,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`                         // IF name on create Virtual Machine
	BridgeName    string                 `protobuf:"bytes,2,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`             // bridge name of the host to which the IF is connected
	Cidr          string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`                                           // CIDR on create Virtual Machine (format: x.x.x.x/y)
	AddressStart  *string                `protobuf:"bytes,4,opt,name=address_start,json=addressStart,proto3,oneof" json:"address_start,omitempty"` // Min. IP range in specified cidr (format: x.x.x.x)
	AddressEnd    *string                `protobuf:"bytes,5,opt,name=address_end,json=addressEnd,proto3,oneof" json:"address_end,omitempty"`       // Max. IP range in specified cidr (format: x.x.x.x)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInformationCni) Reset() {
	*x = NetworkInformationCni{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInformationCni) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInformationCni) ProtoMessage() {}

func (x *NetworkInformationCni) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInformationCni.ProtoReflect.Descriptor instead.
func (*NetworkInformationCni) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkInformationCni) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *NetworkInformationCni) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *NetworkInformationCni) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkInformationCni) GetAddressStart() string {
	if x != nil && x.AddressStart != nil {
		return *x.AddressStart
	}
	return ""
}

func (x *NetworkInformationCni) GetAddressEnd() string {
	if x != nil && x.AddressEnd != nil {
		return *x.AddressEnd
	}
	return ""
}

// Request message for MachineRegister
type MachineRegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo        *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"` // Product information
	MaasInfo           *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`          // MAAS information
	HostName           string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`          // host name
	MacAddress         string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpmiAddress        string                 `protobuf:"bytes,5,opt,name=ipmi_address,json=ipmiAddress,proto3" json:"ipmi_address,omitempty"`                      // IPMI IP address for specified machine (format: x.x.x.x)
	IpmiUser           string                 `protobuf:"bytes,6,opt,name=ipmi_user,json=ipmiUser,proto3" json:"ipmi_user,omitempty"`                               // IPMI login user for specified machine
	IpmiPassword       string                 `protobuf:"bytes,7,opt,name=ipmi_password,json=ipmiPassword,proto3" json:"ipmi_password,omitempty"`                   // IPMI login password for specified machine
	NetworkInformation []*NetworkInformation  `protobuf:"bytes,8,rep,name=network_information,json=networkInformation,proto3" json:"network_information,omitempty"` // Network information list
	ExtraParameter     *string                `protobuf:"bytes,9,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"`       // Product extension parameters
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MachineRegisterRequest) Reset() {
	*x = MachineRegisterRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRegisterRequest) ProtoMessage() {}

func (x *MachineRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRegisterRequest.ProtoReflect.Descriptor instead.
func (*MachineRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{5}
}

func (x *MachineRegisterRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineRegisterRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *MachineRegisterRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *MachineRegisterRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *MachineRegisterRequest) GetIpmiAddress() string {
	if x != nil {
		return x.IpmiAddress
	}
	return ""
}

func (x *MachineRegisterRequest) GetIpmiUser() string {
	if x != nil {
		return x.IpmiUser
	}
	return ""
}

func (x *MachineRegisterRequest) GetIpmiPassword() string {
	if x != nil {
		return x.IpmiPassword
	}
	return ""
}

func (x *MachineRegisterRequest) GetNetworkInformation() []*NetworkInformation {
	if x != nil {
		return x.NetworkInformation
	}
	return nil
}

func (x *MachineRegisterRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineRegister
type MachineRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`             // system-id managed by MaaS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineRegisterResponse) Reset() {
	*x = MachineRegisterResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRegisterResponse) ProtoMessage() {}

func (x *MachineRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRegisterResponse.ProtoReflect.Descriptor instead.
func (*MachineRegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{6}
}

func (x *MachineRegisterResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineRegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MachineRegisterResponse) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

// Request message for MachineDelete
type MachineDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineDeleteRequest) Reset() {
	*x = MachineDeleteRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDeleteRequest) ProtoMessage() {}

func (x *MachineDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDeleteRequest.ProtoReflect.Descriptor instead.
func (*MachineDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{7}
}

func (x *MachineDeleteRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineDeleteRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *MachineDeleteRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *MachineDeleteRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineDelete
type MachineDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDeleteResponse) Reset() {
	*x = MachineDeleteResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDeleteResponse) ProtoMessage() {}

func (x *MachineDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDeleteResponse.ProtoReflect.Descriptor instead.
func (*MachineDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{8}
}

func (x *MachineDeleteResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineDeleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for OsDeploy
type OsDeployRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	VmFlag         *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=vm_flag,json=vmFlag,proto3" json:"vm_flag,omitempty"`                               // flag for vm host
	Os             *OsInformation         `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`                                                     // OS information
	UserData       string                 `protobuf:"bytes,6,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`                         // User data for cloud init
	ExtraParameter *string                `protobuf:"bytes,7,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OsDeployRequest) Reset() {
	*x = OsDeployRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsDeployRequest) ProtoMessage() {}

func (x *OsDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsDeployRequest.ProtoReflect.Descriptor instead.
func (*OsDeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{9}
}

func (x *OsDeployRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *OsDeployRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *OsDeployRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *OsDeployRequest) GetVmFlag() *wrapperspb.BoolValue {
	if x != nil {
		return x.VmFlag
	}
	return nil
}

func (x *OsDeployRequest) GetOs() *OsInformation {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *OsDeployRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *OsDeployRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for OsDeploy
type OsDeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsDeployResponse) Reset() {
	*x = OsDeployResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsDeployResponse) ProtoMessage() {}

func (x *OsDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsDeployResponse.ProtoReflect.Descriptor instead.
func (*OsDeployResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{10}
}

func (x *OsDeployResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *OsDeployResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for OsRelease
type OsReleaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OsReleaseRequest) Reset() {
	*x = OsReleaseRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsReleaseRequest) ProtoMessage() {}

func (x *OsReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsReleaseRequest.ProtoReflect.Descriptor instead.
func (*OsReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{11}
}

func (x *OsReleaseRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *OsReleaseRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *OsReleaseRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *OsReleaseRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for OsRelease
type OsReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsReleaseResponse) Reset() {
	*x = OsReleaseResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsReleaseResponse) ProtoMessage() {}

func (x *OsReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsReleaseResponse.ProtoReflect.Descriptor instead.
func (*OsReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{12}
}

func (x *OsReleaseResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *OsReleaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for VmCompose
type VmComposeRequest struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ProductInfo        *ProductInformation      `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                      // Product information
	MaasInfo           *MaasInformation         `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                               // MAAS information
	SystemId           string                   `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                               // system-id managed by MaaS (for host machine)
	HostName           string                   `protobuf:"bytes,4,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`                               // host name (for guest-vm)
	CpuCore            *int32                   `protobuf:"varint,5,opt,name=cpu_core,json=cpuCore,proto3,oneof" json:"cpu_core,omitempty"`                           // core of CPU
	Memory             *int32                   `protobuf:"varint,6,opt,name=memory,proto3,oneof" json:"memory,omitempty"`                                            // memory (MiB)
	DiskSize           *int32                   `protobuf:"varint,7,opt,name=disk_size,json=diskSize,proto3,oneof" json:"disk_size,omitempty"`                        // disk size (GB)
	NetworkInformation []*NetworkInformationCni `protobuf:"bytes,8,rep,name=network_information,json=networkInformation,proto3" json:"network_information,omitempty"` // Network information list
	ExtraParameter     *string                  `protobuf:"bytes,9,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"`       // Product extension parameters
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VmComposeRequest) Reset() {
	*x = VmComposeRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmComposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmComposeRequest) ProtoMessage() {}

func (x *VmComposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmComposeRequest.ProtoReflect.Descriptor instead.
func (*VmComposeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{13}
}

func (x *VmComposeRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VmComposeRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *VmComposeRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *VmComposeRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *VmComposeRequest) GetCpuCore() int32 {
	if x != nil && x.CpuCore != nil {
		return *x.CpuCore
	}
	return 0
}

func (x *VmComposeRequest) GetMemory() int32 {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return 0
}

func (x *VmComposeRequest) GetDiskSize() int32 {
	if x != nil && x.DiskSize != nil {
		return *x.DiskSize
	}
	return 0
}

func (x *VmComposeRequest) GetNetworkInformation() []*NetworkInformationCni {
	if x != nil {
		return x.NetworkInformation
	}
	return nil
}

func (x *VmComposeRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VmCompose
type VmComposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`             // system-id managed by MaaS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmComposeResponse) Reset() {
	*x = VmComposeResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmComposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmComposeResponse) ProtoMessage() {}

func (x *VmComposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmComposeResponse.ProtoReflect.Descriptor instead.
func (*VmComposeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{14}
}

func (x *VmComposeResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VmComposeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VmComposeResponse) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

// Request message for VmDelete
type VmDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VmDeleteRequest) Reset() {
	*x = VmDeleteRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDeleteRequest) ProtoMessage() {}

func (x *VmDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDeleteRequest.ProtoReflect.Descriptor instead.
func (*VmDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{15}
}

func (x *VmDeleteRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VmDeleteRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *VmDeleteRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *VmDeleteRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VmDelete
type VmDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmDeleteResponse) Reset() {
	*x = VmDeleteResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDeleteResponse) ProtoMessage() {}

func (x *VmDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDeleteResponse.ProtoReflect.Descriptor instead.
func (*VmDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{16}
}

func (x *VmDeleteResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VmDeleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for MachineList
type MachineListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	ExtraParameter *string                `protobuf:"bytes,3,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineListRequest) Reset() {
	*x = MachineListRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListRequest) ProtoMessage() {}

func (x *MachineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListRequest.ProtoReflect.Descriptor instead.
func (*MachineListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{17}
}

func (x *MachineListRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineListRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *MachineListRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineList
type MachineListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // information of machine-list (JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineListResponse) Reset() {
	*x = MachineListResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineListResponse) ProtoMessage() {}

func (x *MachineListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineListResponse.ProtoReflect.Descriptor instead.
func (*MachineListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{18}
}

func (x *MachineListResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MachineListResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Request message for MachineShow
type MachineShowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineShowRequest) Reset() {
	*x = MachineShowRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineShowRequest) ProtoMessage() {}

func (x *MachineShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineShowRequest.ProtoReflect.Descriptor instead.
func (*MachineShowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{19}
}

func (x *MachineShowRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *MachineShowRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *MachineShowRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *MachineShowRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for MachineShow
type MachineShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                     // information of a machine (JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineShowResponse) Reset() {
	*x = MachineShowResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineShowResponse) ProtoMessage() {}

func (x *MachineShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineShowResponse.ProtoReflect.Descriptor instead.
func (*MachineShowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{20}
}

func (x *MachineShowResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *MachineShowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MachineShowResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Request message for Cancel
type CancelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	MaasInfo       *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                         // MAAS information
	SystemId       string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                         // system-id managed by MaaS
	ExtraParameter *string                `protobuf:"bytes,4,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{21}
}

func (x *CancelRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *CancelRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *CancelRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *CancelRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for Cancel
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{22}
}

func (x *CancelResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *CancelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for NetworkUpdate
type NetworkUpdateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo        *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                      // Product information
	MaasInfo           *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`                               // MAAS information
	SystemId           string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                               // system-id managed by MaaS
	NetworkInformation []*NetworkInformation  `protobuf:"bytes,4,rep,name=network_information,json=networkInformation,proto3" json:"network_information,omitempty"` // Network information list
	UserData           string                 `protobuf:"bytes,5,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`                               // User data for cloud init
	ExtraParameter     *string                `protobuf:"bytes,6,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"`       // Product extension parameters
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkUpdateRequest) Reset() {
	*x = NetworkUpdateRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUpdateRequest) ProtoMessage() {}

func (x *NetworkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUpdateRequest.ProtoReflect.Descriptor instead.
func (*NetworkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{23}
}

func (x *NetworkUpdateRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *NetworkUpdateRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *NetworkUpdateRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *NetworkUpdateRequest) GetNetworkInformation() []*NetworkInformation {
	if x != nil {
		return x.NetworkInformation
	}
	return nil
}

func (x *NetworkUpdateRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *NetworkUpdateRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for NetworkUpdate
type NetworkUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkUpdateResponse) Reset() {
	*x = NetworkUpdateResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUpdateResponse) ProtoMessage() {}

func (x *NetworkUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUpdateResponse.ProtoReflect.Descriptor instead.
func (*NetworkUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkUpdateResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *NetworkUpdateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for PowerOn
type PowerOnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo   *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"` // Product information
	MaasInfo      *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`          // MAAS information
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`          // system-id managed by MaaS
	UserData      string                 `protobuf:"bytes,4,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`          // User data for cloud init
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnRequest) Reset() {
	*x = PowerOnRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnRequest) ProtoMessage() {}

func (x *PowerOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnRequest.ProtoReflect.Descriptor instead.
func (*PowerOnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{25}
}

func (x *PowerOnRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *PowerOnRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *PowerOnRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *PowerOnRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

// Response message for PowerOn
type PowerOnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnResponse) Reset() {
	*x = PowerOnResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnResponse) ProtoMessage() {}

func (x *PowerOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnResponse.ProtoReflect.Descriptor instead.
func (*PowerOnResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{26}
}

func (x *PowerOnResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *PowerOnResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for PowerOff
type PowerOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo   *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"` // Product information
	MaasInfo      *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`          // MAAS information
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`          // system-id managed by MaaS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOffRequest) Reset() {
	*x = PowerOffRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOffRequest) ProtoMessage() {}

func (x *PowerOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOffRequest.ProtoReflect.Descriptor instead.
func (*PowerOffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{27}
}

func (x *PowerOffRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *PowerOffRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *PowerOffRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

// Response message for PowerOff
type PowerOffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOffResponse) Reset() {
	*x = PowerOffResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOffResponse) ProtoMessage() {}

func (x *PowerOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOffResponse.ProtoReflect.Descriptor instead.
func (*PowerOffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{28}
}

func (x *PowerOffResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *PowerOffResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for KubeadmReset
type KubeadmResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo   *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"` // Product information
	MaasInfo      *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`          // MAAS information
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`          // system-id managed by MaaS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeadmResetRequest) Reset() {
	*x = KubeadmResetRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmResetRequest) ProtoMessage() {}

func (x *KubeadmResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeadmResetRequest.ProtoReflect.Descriptor instead.
func (*KubeadmResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{29}
}

func (x *KubeadmResetRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *KubeadmResetRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *KubeadmResetRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

// Response message for KubeadmReset
type KubeadmResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeadmResetResponse) Reset() {
	*x = KubeadmResetResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmResetResponse) ProtoMessage() {}

func (x *KubeadmResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeadmResetResponse.ProtoReflect.Descriptor instead.
func (*KubeadmResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{30}
}

func (x *KubeadmResetResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *KubeadmResetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for KubeadmJoin
type KubeadmJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo   *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"` // Product information
	MaasInfo      *MaasInformation       `protobuf:"bytes,2,opt,name=maas_info,json=maasInfo,proto3" json:"maas_info,omitempty"`          // MAAS information
	SystemId      string                 `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`          // system-id managed by MaaS
	CpSystemId    []string               `protobuf:"bytes,4,rep,name=cp_system_id,json=cpSystemId,proto3" json:"cp_system_id,omitempty"`  // system-id managed by MaaS For CP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeadmJoinRequest) Reset() {
	*x = KubeadmJoinRequest{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmJoinRequest) ProtoMessage() {}

func (x *KubeadmJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeadmJoinRequest.ProtoReflect.Descriptor instead.
func (*KubeadmJoinRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{31}
}

func (x *KubeadmJoinRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *KubeadmJoinRequest) GetMaasInfo() *MaasInformation {
	if x != nil {
		return x.MaasInfo
	}
	return nil
}

func (x *KubeadmJoinRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *KubeadmJoinRequest) GetCpSystemId() []string {
	if x != nil {
		return x.CpSystemId
	}
	return nil
}

// Response message for KubeadmJoin
type KubeadmJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (ACCEPT or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeadmJoinResponse) Reset() {
	*x = KubeadmJoinResponse{}
	mi := &file_api_proto_maas_interface_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeadmJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeadmJoinResponse) ProtoMessage() {}

func (x *KubeadmJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_maas_interface_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeadmJoinResponse.ProtoReflect.Descriptor instead.
func (*KubeadmJoinResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_maas_interface_proto_rawDescGZIP(), []int{32}
}

func (x *KubeadmJoinResponse) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *KubeadmJoinResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_maas_interface_proto protoreflect.FileDescriptor

const file_api_proto_maas_interface_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/maas_interface.proto\x12\tprotomaas\x1a\x17validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a'common/api/proto/common_interface.proto\"\xb5\x01\n" +
	"\x12ProductInformation\x12\"\n" +
	"\x06vendor\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\x06vendor\x12-\n" +
	"\fproduct_name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\vproductName\x12$\n" +
	"\aversion\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\aversion\x12\x1f\n" +
	"\x02os\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01H\x00R\x02os\x88\x01\x01B\x05\n" +
	"\x03_os\"a\n" +
	"\x0fMaasInformation\x12)\n" +
	"\n" +
	"access_url\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\taccessUrl\x12#\n" +
	"\aapi_key\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x06apiKey\"\xf8\x02\n" +
	"\x12NetworkInformation\x12R\n" +
	"\vmac_address\x18\x01 \x01(\tB1\xfaB.r,\x10\x01\x18\x112&^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$R\n" +
	"macAddress\x12\x89\x01\n" +
	"\x04cidr\x18\x02 \x01(\tBu\xfaBrrp\x10\x01\x18\x122j^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/(3[0-2]|[1-2]?[0-9])$R\x04cidr\x121\n" +
	"\raddress_start\x18\x03 \x01(\tB\a\xfaB\x04r\x02x\x01H\x00R\faddressStart\x88\x01\x01\x12-\n" +
	"\vaddress_end\x18\x04 \x01(\tB\a\xfaB\x04r\x02x\x01H\x01R\n" +
	"addressEnd\x88\x01\x01B\x10\n" +
	"\x0e_address_startB\x0e\n" +
	"\f_address_end\"c\n" +
	"\rOsInformation\x12-\n" +
	"\fdistribution\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\fdistribution\x12#\n" +
	"\aversion\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\aversion\"\xf7\x02\n" +
	"\x15NetworkInformationCni\x12\"\n" +
	"\aif_name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x0fR\x06ifName\x12*\n" +
	"\vbridge_name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x0fR\n" +
	"bridgeName\x12\x89\x01\n" +
	"\x04cidr\x18\x03 \x01(\tBu\xfaBrrp\x10\x01\x18\x122j^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/(3[0-2]|[1-2]?[0-9])$R\x04cidr\x121\n" +
	"\raddress_start\x18\x04 \x01(\tB\a\xfaB\x04r\x02x\x01H\x00R\faddressStart\x88\x01\x01\x12-\n" +
	"\vaddress_end\x18\x05 \x01(\tB\a\xfaB\x04r\x02x\x01H\x01R\n" +
	"addressEnd\x88\x01\x01B\x10\n" +
	"\x0e_address_startB\x0e\n" +
	"\f_address_end\"\xc4\x04\n" +
	"\x16MachineRegisterRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12'\n" +
	"\thost_name\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\bhostName\x12R\n" +
	"\vmac_address\x18\x04 \x01(\tB1\xfaB.r,\x10\x01\x18\x112&^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$R\n" +
	"macAddress\x12*\n" +
	"\fipmi_address\x18\x05 \x01(\tB\a\xfaB\x04r\x02x\x01R\vipmiAddress\x12&\n" +
	"\tipmi_user\x18\x06 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\bipmiUser\x12.\n" +
	"\ripmi_password\x18\a \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\fipmiPassword\x12X\n" +
	"\x13network_information\x18\b \x03(\v2\x1d.protomaas.NetworkInformationB\b\xfaB\x05\x92\x01\x02\b\x01R\x12networkInformation\x12,\n" +
	"\x0fextra_parameter\x18\t \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x97\x01\n" +
	"\x17MachineRegisterResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tsystem_id\x18\x03 \x01(\tR\bsystemIdB\t\n" +
	"\a_result\"\x8f\x02\n" +
	"\x14MachineDeleteRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"x\n" +
	"\x15MachineDeleteResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\x9a\x03\n" +
	"\x0fOsDeployRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12=\n" +
	"\avm_flag\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06vmFlag\x122\n" +
	"\x02os\x18\x05 \x01(\v2\x18.protomaas.OsInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x02os\x12\x1b\n" +
	"\tuser_data\x18\x06 \x01(\tR\buserData\x12,\n" +
	"\x0fextra_parameter\x18\a \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"s\n" +
	"\x10OsDeployResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\x8b\x02\n" +
	"\x10OsReleaseRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"t\n" +
	"\x11OsReleaseResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xbd\x04\n" +
	"\x10VmComposeRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12'\n" +
	"\thost_name\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\bhostName\x12+\n" +
	"\bcpu_core\x18\x05 \x01(\x05B\v\xfaB\b\x1a\x06\x18\x9f\x8d\x06(\x01H\x00R\acpuCore\x88\x01\x01\x12)\n" +
	"\x06memory\x18\x06 \x01(\x05B\f\xfaB\t\x1a\a\x18\xff\xc1\xd7/(\x01H\x01R\x06memory\x88\x01\x01\x12,\n" +
	"\tdisk_size\x18\a \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xc0\a(\x01H\x02R\bdiskSize\x88\x01\x01\x12[\n" +
	"\x13network_information\x18\b \x03(\v2 .protomaas.NetworkInformationCniB\b\xfaB\x05\x92\x01\x02\b\x01R\x12networkInformation\x12,\n" +
	"\x0fextra_parameter\x18\t \x01(\tH\x03R\x0eextraParameter\x88\x01\x01B\v\n" +
	"\t_cpu_coreB\t\n" +
	"\a_memoryB\f\n" +
	"\n" +
	"_disk_sizeB\x12\n" +
	"\x10_extra_parameter\"\x91\x01\n" +
	"\x11VmComposeResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tsystem_id\x18\x03 \x01(\tR\bsystemIdB\t\n" +
	"\a_result\"\x8a\x02\n" +
	"\x0fVmDeleteRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"s\n" +
	"\x10VmDeleteResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xe5\x01\n" +
	"\x12MachineListRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12,\n" +
	"\x0fextra_parameter\x18\x03 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x8a\x01\n" +
	"\x13MachineListResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB\t\n" +
	"\a_result\"\x8d\x02\n" +
	"\x12MachineShowRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"\x8a\x01\n" +
	"\x13MachineShowResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB\t\n" +
	"\a_result\"\x88\x02\n" +
	"\rCancelRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12,\n" +
	"\x0fextra_parameter\x18\x04 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"q\n" +
	"\x0eCancelResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\x86\x03\n" +
	"\x14NetworkUpdateRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12X\n" +
	"\x13network_information\x18\x04 \x03(\v2\x1d.protomaas.NetworkInformationB\b\xfaB\x05\x92\x01\x02\b\x01R\x12networkInformation\x12\x1b\n" +
	"\tuser_data\x18\x05 \x01(\tR\buserData\x12,\n" +
	"\x0fextra_parameter\x18\x06 \x01(\tH\x00R\x0eextraParameter\x88\x01\x01B\x12\n" +
	"\x10_extra_parameter\"x\n" +
	"\x15NetworkUpdateResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xe4\x01\n" +
	"\x0ePowerOnRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x12\x1b\n" +
	"\tuser_data\x18\x04 \x01(\tR\buserData\"r\n" +
	"\x0fPowerOnResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xc8\x01\n" +
	"\x0fPowerOffRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\"s\n" +
	"\x10PowerOffResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xcc\x01\n" +
	"\x13KubeadmResetRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\"w\n" +
	"\x14KubeadmResetResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xff\x01\n" +
	"\x12KubeadmJoinRequest\x12J\n" +
	"\fproduct_info\x18\x01 \x01(\v2\x1d.protomaas.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12A\n" +
	"\tmaas_info\x18\x02 \x01(\v2\x1a.protomaas.MaasInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bmaasInfo\x12&\n" +
	"\tsystem_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x06R\bsystemId\x122\n" +
	"\fcp_system_id\x18\x04 \x03(\tB\x10\xfaB\r\x92\x01\n" +
	"\b\x01\"\x06r\x04\x10\x01\x18\x06R\n" +
	"cpSystemId\"v\n" +
	"\x13KubeadmJoinResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result*\xb0\x01\n" +
	"\n" +
	"DetailCode\x12\b\n" +
	"\x04ZERO\x10\x00\x12\x18\n" +
	"\x14IF_PARAMETER_INVALID\x10)\x12\x15\n" +
	"\x11UNSUPPORT_PRODUCT\x10*\x12\x15\n" +
	"\x11IF_SEQUENCE_ERROR\x104\x12\x19\n" +
	"\x15IF_CANCEL_UNAVAILABLE\x105\x12\x1a\n" +
	"\x16MAAS_ENVIRONMENT_ERROR\x10=\x12\x19\n" +
	"\x15MAAS_RESPONSE_INVALID\x10Q2\xbf\b\n" +
	"\x04Maas\x12Z\n" +
	"\x0fMachineRegister\x12!.protomaas.MachineRegisterRequest\x1a\".protomaas.MachineRegisterResponse\"\x00\x12T\n" +
	"\rMachineDelete\x12\x1f.protomaas.MachineDeleteRequest\x1a .protomaas.MachineDeleteResponse\"\x00\x12E\n" +
	"\bOsDeploy\x12\x1a.protomaas.OsDeployRequest\x1a\x1b.protomaas.OsDeployResponse\"\x00\x12H\n" +
	"\tOsRelease\x12\x1b.protomaas.OsReleaseRequest\x1a\x1c.protomaas.OsReleaseResponse\"\x00\x12H\n" +
	"\tVmCompose\x12\x1b.protomaas.VmComposeRequest\x1a\x1c.protomaas.VmComposeResponse\"\x00\x12E\n" +
	"\bVmDelete\x12\x1a.protomaas.VmDeleteRequest\x1a\x1b.protomaas.VmDeleteResponse\"\x00\x12N\n" +
	"\vMachineList\x12\x1d.protomaas.MachineListRequest\x1a\x1e.protomaas.MachineListResponse\"\x00\x12N\n" +
	"\vMachineShow\x12\x1d.protomaas.MachineShowRequest\x1a\x1e.protomaas.MachineShowResponse\"\x00\x12?\n" +
	"\x06Cancel\x12\x18.protomaas.CancelRequest\x1a\x19.protomaas.CancelResponse\"\x00\x12T\n" +
	"\rNetworkUpdate\x12\x1f.protomaas.NetworkUpdateRequest\x1a .protomaas.NetworkUpdateResponse\"\x00\x12B\n" +
	"\aPowerOn\x12\x19.protomaas.PowerOnRequest\x1a\x1a.protomaas.PowerOnResponse\"\x00\x12E\n" +
	"\bPowerOff\x12\x1a.protomaas.PowerOffRequest\x1a\x1b.protomaas.PowerOffResponse\"\x00\x12Q\n" +
	"\fKubeadmReset\x12\x1e.protomaas.KubeadmResetRequest\x1a\x1f.protomaas.KubeadmResetResponse\"\x00\x12N\n" +
	"\vKubeadmJoin\x12\x1d.protomaas.KubeadmJoinRequest\x1a\x1e.protomaas.KubeadmJoinResponse\"\x00B!Z\x1fmaas_module/api/proto;protomaasb\x06proto3"

var (
	file_api_proto_maas_interface_proto_rawDescOnce sync.Once
	file_api_proto_maas_interface_proto_rawDescData []byte
)

func file_api_proto_maas_interface_proto_rawDescGZIP() []byte {
	file_api_proto_maas_interface_proto_rawDescOnce.Do(func() {
		file_api_proto_maas_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_maas_interface_proto_rawDesc), len(file_api_proto_maas_interface_proto_rawDesc)))
	})
	return file_api_proto_maas_interface_proto_rawDescData
}

var file_api_proto_maas_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_maas_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_proto_maas_interface_proto_goTypes = []any{
	(DetailCode)(0),                 // 0: protomaas.DetailCode
	(*ProductInformation)(nil),      // 1: protomaas.ProductInformation
	(*MaasInformation)(nil),         // 2: protomaas.MaasInformation
	(*NetworkInformation)(nil),      // 3: protomaas.NetworkInformation
	(*OsInformation)(nil),           // 4: protomaas.OsInformation
	(*NetworkInformationCni)(nil),   // 5: protomaas.NetworkInformationCni
	(*MachineRegisterRequest)(nil),  // 6: protomaas.MachineRegisterRequest
	(*MachineRegisterResponse)(nil), // 7: protomaas.MachineRegisterResponse
	(*MachineDeleteRequest)(nil),    // 8: protomaas.MachineDeleteRequest
	(*MachineDeleteResponse)(nil),   // 9: protomaas.MachineDeleteResponse
	(*OsDeployRequest)(nil),         // 10: protomaas.OsDeployRequest
	(*OsDeployResponse)(nil),        // 11: protomaas.OsDeployResponse
	(*OsReleaseRequest)(nil),        // 12: protomaas.OsReleaseRequest
	(*OsReleaseResponse)(nil),       // 13: protomaas.OsReleaseResponse
	(*VmComposeRequest)(nil),        // 14: protomaas.VmComposeRequest
	(*VmComposeResponse)(nil),       // 15: protomaas.VmComposeResponse
	(*VmDeleteRequest)(nil),         // 16: protomaas.VmDeleteRequest
	(*VmDeleteResponse)(nil),        // 17: protomaas.VmDeleteResponse
	(*MachineListRequest)(nil),      // 18: protomaas.MachineListRequest
	(*MachineListResponse)(nil),     // 19: protomaas.MachineListResponse
	(*MachineShowRequest)(nil),      // 20: protomaas.MachineShowRequest
	(*MachineShowResponse)(nil),     // 21: protomaas.MachineShowResponse
	(*CancelRequest)(nil),           // 22: protomaas.CancelRequest
	(*CancelResponse)(nil),          // 23: protomaas.CancelResponse
	(*NetworkUpdateRequest)(nil),    // 24: protomaas.NetworkUpdateRequest
	(*NetworkUpdateResponse)(nil),   // 25: protomaas.NetworkUpdateResponse
	(*PowerOnRequest)(nil),          // 26: protomaas.PowerOnRequest
	(*PowerOnResponse)(nil),         // 27: protomaas.PowerOnResponse
	(*PowerOffRequest)(nil),         // 28: protomaas.PowerOffRequest
	(*PowerOffResponse)(nil),        // 29: protomaas.PowerOffResponse
	(*KubeadmResetRequest)(nil),     // 30: protomaas.KubeadmResetRequest
	(*KubeadmResetResponse)(nil),    // 31: protomaas.KubeadmResetResponse
	(*KubeadmJoinRequest)(nil),      // 32: protomaas.KubeadmJoinRequest
	(*KubeadmJoinResponse)(nil),     // 33: protomaas.KubeadmJoinResponse
	(proto.ResultCode)(0),           // 34: common.ResultCode
	(*wrapperspb.BoolValue)(nil),    // 35: google.protobuf.BoolValue
}
var file_api_proto_maas_interface_proto_depIdxs = []int32{
	1,  // 0: protomaas.MachineRegisterRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 1: protomaas.MachineRegisterRequest.maas_info:type_name -> protomaas.MaasInformation
	3,  // 2: protomaas.MachineRegisterRequest.network_information:type_name -> protomaas.NetworkInformation
	34, // 3: protomaas.MachineRegisterResponse.result:type_name -> common.ResultCode
	1,  // 4: protomaas.MachineDeleteRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 5: protomaas.MachineDeleteRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 6: protomaas.MachineDeleteResponse.result:type_name -> common.ResultCode
	1,  // 7: protomaas.OsDeployRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 8: protomaas.OsDeployRequest.maas_info:type_name -> protomaas.MaasInformation
	35, // 9: protomaas.OsDeployRequest.vm_flag:type_name -> google.protobuf.BoolValue
	4,  // 10: protomaas.OsDeployRequest.os:type_name -> protomaas.OsInformation
	34, // 11: protomaas.OsDeployResponse.result:type_name -> common.ResultCode
	1,  // 12: protomaas.OsReleaseRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 13: protomaas.OsReleaseRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 14: protomaas.OsReleaseResponse.result:type_name -> common.ResultCode
	1,  // 15: protomaas.VmComposeRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 16: protomaas.VmComposeRequest.maas_info:type_name -> protomaas.MaasInformation
	5,  // 17: protomaas.VmComposeRequest.network_information:type_name -> protomaas.NetworkInformationCni
	34, // 18: protomaas.VmComposeResponse.result:type_name -> common.ResultCode
	1,  // 19: protomaas.VmDeleteRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 20: protomaas.VmDeleteRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 21: protomaas.VmDeleteResponse.result:type_name -> common.ResultCode
	1,  // 22: protomaas.MachineListRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 23: protomaas.MachineListRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 24: protomaas.MachineListResponse.result:type_name -> common.ResultCode
	1,  // 25: protomaas.MachineShowRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 26: protomaas.MachineShowRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 27: protomaas.MachineShowResponse.result:type_name -> common.ResultCode
	1,  // 28: protomaas.CancelRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 29: protomaas.CancelRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 30: protomaas.CancelResponse.result:type_name -> common.ResultCode
	1,  // 31: protomaas.NetworkUpdateRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 32: protomaas.NetworkUpdateRequest.maas_info:type_name -> protomaas.MaasInformation
	3,  // 33: protomaas.NetworkUpdateRequest.network_information:type_name -> protomaas.NetworkInformation
	34, // 34: protomaas.NetworkUpdateResponse.result:type_name -> common.ResultCode
	1,  // 35: protomaas.PowerOnRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 36: protomaas.PowerOnRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 37: protomaas.PowerOnResponse.result:type_name -> common.ResultCode
	1,  // 38: protomaas.PowerOffRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 39: protomaas.PowerOffRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 40: protomaas.PowerOffResponse.result:type_name -> common.ResultCode
	1,  // 41: protomaas.KubeadmResetRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 42: protomaas.KubeadmResetRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 43: protomaas.KubeadmResetResponse.result:type_name -> common.ResultCode
	1,  // 44: protomaas.KubeadmJoinRequest.product_info:type_name -> protomaas.ProductInformation
	2,  // 45: protomaas.KubeadmJoinRequest.maas_info:type_name -> protomaas.MaasInformation
	34, // 46: protomaas.KubeadmJoinResponse.result:type_name -> common.ResultCode
	6,  // 47: protomaas.Maas.MachineRegister:input_type -> protomaas.MachineRegisterRequest
	8,  // 48: protomaas.Maas.MachineDelete:input_type -> protomaas.MachineDeleteRequest
	10, // 49: protomaas.Maas.OsDeploy:input_type -> protomaas.OsDeployRequest
	12, // 50: protomaas.Maas.OsRelease:input_type -> protomaas.OsReleaseRequest
	14, // 51: protomaas.Maas.VmCompose:input_type -> protomaas.VmComposeRequest
	16, // 52: protomaas.Maas.VmDelete:input_type -> protomaas.VmDeleteRequest
	18, // 53: protomaas.Maas.MachineList:input_type -> protomaas.MachineListRequest
	20, // 54: protomaas.Maas.MachineShow:input_type -> protomaas.MachineShowRequest
	22, // 55: protomaas.Maas.Cancel:input_type -> protomaas.CancelRequest
	24, // 56: protomaas.Maas.NetworkUpdate:input_type -> protomaas.NetworkUpdateRequest
	26, // 57: protomaas.Maas.PowerOn:input_type -> protomaas.PowerOnRequest
	28, // 58: protomaas.Maas.PowerOff:input_type -> protomaas.PowerOffRequest
	30, // 59: protomaas.Maas.KubeadmReset:input_type -> protomaas.KubeadmResetRequest
	32, // 60: protomaas.Maas.KubeadmJoin:input_type -> protomaas.KubeadmJoinRequest
	7,  // 61: protomaas.Maas.MachineRegister:output_type -> protomaas.MachineRegisterResponse
	9,  // 62: protomaas.Maas.MachineDelete:output_type -> protomaas.MachineDeleteResponse
	11, // 63: protomaas.Maas.OsDeploy:output_type -> protomaas.OsDeployResponse
	13, // 64: protomaas.Maas.OsRelease:output_type -> protomaas.OsReleaseResponse
	15, // 65: protomaas.Maas.VmCompose:output_type -> protomaas.VmComposeResponse
	17, // 66: protomaas.Maas.VmDelete:output_type -> protomaas.VmDeleteResponse
	19, // 67: protomaas.Maas.MachineList:output_type -> protomaas.MachineListResponse
	21, // 68: protomaas.Maas.MachineShow:output_type -> protomaas.MachineShowResponse
	23, // 69: protomaas.Maas.Cancel:output_type -> protomaas.CancelResponse
	25, // 70: protomaas.Maas.NetworkUpdate:output_type -> protomaas.NetworkUpdateResponse
	27, // 71: protomaas.Maas.PowerOn:output_type -> protomaas.PowerOnResponse
	29, // 72: protomaas.Maas.PowerOff:output_type -> protomaas.PowerOffResponse
	31, // 73: protomaas.Maas.KubeadmReset:output_type -> protomaas.KubeadmResetResponse
	33, // 74: protomaas.Maas.KubeadmJoin:output_type -> protomaas.KubeadmJoinResponse
	61, // [61:75] is the sub-list for method output_type
	47, // [47:61] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_api_proto_maas_interface_proto_init() }
func file_api_proto_maas_interface_proto_init() {
	if File_api_proto_maas_interface_proto != nil {
		return
	}
	file_api_proto_maas_interface_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[20].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[21].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[22].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[23].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[24].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[26].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[28].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[30].OneofWrappers = []any{}
	file_api_proto_maas_interface_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_maas_interface_proto_rawDesc), len(file_api_proto_maas_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_maas_interface_proto_goTypes,
		DependencyIndexes: file_api_proto_maas_interface_proto_depIdxs,
		EnumInfos:         file_api_proto_maas_interface_proto_enumTypes,
		MessageInfos:      file_api_proto_maas_interface_proto_msgTypes,
	}.Build()
	File_api_proto_maas_interface_proto = out.File
	file_api_proto_maas_interface_proto_goTypes = nil
	file_api_proto_maas_interface_proto_depIdxs = nil
}
