apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "network") }}-service
spec:
  selector:
    app: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "network") }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.serverPort }}
  type: {{ .Values.service.type }}
