// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/common_interface.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for processing result
type ResultCode int32

const (
	ResultCode_ACCEPT  ResultCode = 0 // Accept
	ResultCode_SUCCESS ResultCode = 1 // Success
	ResultCode_ERROR   ResultCode = 2 // Error
)

// Enum value maps for ResultCode.
var (
	ResultCode_name = map[int32]string{
		0: "ACCEPT",
		1: "SUCCESS",
		2: "ERROR",
	}
	ResultCode_value = map[string]int32{
		"ACCEPT":  0,
		"SUCCESS": 1,
		"ERROR":   2,
	}
)

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_interface_proto_enumTypes[0].Descriptor()
}

func (ResultCode) Type() protoreflect.EnumType {
	return &file_api_proto_common_interface_proto_enumTypes[0]
}

func (x ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultCode.Descriptor instead.
func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_interface_proto_rawDescGZIP(), []int{0}
}

// Error message structure
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`   // error code
	DetailCode    int32                  `protobuf:"varint,2,opt,name=detailCode,proto3" json:"detailCode,omitempty"` // detail code
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`        // error code message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_api_proto_common_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_common_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorMessage) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorMessage) GetDetailCode() int32 {
	if x != nil {
		return x.DetailCode
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_common_interface_proto protoreflect.FileDescriptor

const file_api_proto_common_interface_proto_rawDesc = "" +
	"\n" +
	" api/proto/common_interface.proto\x12\x06common\"f\n" +
	"\fErrorMessage\x12\x1c\n" +
	"\terrorCode\x18\x01 \x01(\x05R\terrorCode\x12\x1e\n" +
	"\n" +
	"detailCode\x18\x02 \x01(\x05R\n" +
	"detailCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*0\n" +
	"\n" +
	"ResultCode\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02B\x19Z\x17common/api/proto;commonb\x06proto3"

var (
	file_api_proto_common_interface_proto_rawDescOnce sync.Once
	file_api_proto_common_interface_proto_rawDescData []byte
)

func file_api_proto_common_interface_proto_rawDescGZIP() []byte {
	file_api_proto_common_interface_proto_rawDescOnce.Do(func() {
		file_api_proto_common_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_interface_proto_rawDesc), len(file_api_proto_common_interface_proto_rawDesc)))
	})
	return file_api_proto_common_interface_proto_rawDescData
}

var file_api_proto_common_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_common_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_common_interface_proto_goTypes = []any{
	(ResultCode)(0),      // 0: common.ResultCode
	(*ErrorMessage)(nil), // 1: common.ErrorMessage
}
var file_api_proto_common_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_common_interface_proto_init() }
func file_api_proto_common_interface_proto_init() {
	if File_api_proto_common_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_interface_proto_rawDesc), len(file_api_proto_common_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_interface_proto_goTypes,
		DependencyIndexes: file_api_proto_common_interface_proto_depIdxs,
		EnumInfos:         file_api_proto_common_interface_proto_enumTypes,
		MessageInfos:      file_api_proto_common_interface_proto_msgTypes,
	}.Build()
	File_api_proto_common_interface_proto = out.File
	file_api_proto_common_interface_proto_goTypes = nil
	file_api_proto_common_interface_proto_depIdxs = nil
}
