- hosts: all
  become: no

  tasks:
    - name: machine show
      import_role:
        name: role_login_cdi
      vars:
        execute_cdi_command: "machine show -m {{ machine_name }} -g {{ group_name }} -o JSON"
