- hosts: all
  become: no

  tasks:
    - name: machine destroy
      import_role:
        name: role_login_cdi
      vars:
        execute_cdi_command: "machine destroy -m {{ machine_name }} -g {{ group_name }}"
