- hosts: all
  become: no

  tasks:
    - name: machine create
      import_role:
        name: role_login_cdi
      vars:
        execute_cdi_command: "machine create -m {{ machine_name }} -g {{ group_name }} -r {{ resource_enum }}"
