// Code generated by MockGen. DO NOT EDIT.
// Source: ../../interfaces/canonical_maas_ansible_interface.go
//
// Generated by this command:
//
//	mockgen -source=../../interfaces/canonical_maas_ansible_interface.go -destination=./mocks/mock_ansible.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMaasAnsible is a mock of MaasAnsible interface.
type MockMaasAnsible struct {
	ctrl     *gomock.Controller
	recorder *MockMaasAnsibleMockRecorder
	isgomock struct{}
}

// MockMaasAnsibleMockRecorder is the mock recorder for MockMaasAnsible.
type MockMaasAnsibleMockRecorder struct {
	mock *MockMaasAnsible
}

// NewMockMaasAnsible creates a new mock instance.
func NewMockMaasAnsible(ctrl *gomock.Controller) *MockMaasAnsible {
	mock := &MockMaasAnsible{ctrl: ctrl}
	mock.recorder = &MockMaasAnsibleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaasAnsible) EXPECT() *MockMaasAnsibleMockRecorder {
	return m.recorder
}

// CmdExecute mocks base method.
func (m *MockMaasAnsible) CmdExecute(ctx context.Context, remoteHost, playbook, extrArgs string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdExecute", ctx, remoteHost, playbook, extrArgs)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CmdExecute indicates an expected call of CmdExecute.
func (mr *MockMaasAnsibleMockRecorder) CmdExecute(ctx, remoteHost, playbook, extrArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdExecute", reflect.TypeOf((*MockMaasAnsible)(nil).CmdExecute), ctx, remoteHost, playbook, extrArgs)
}
