// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/maas_api/basis_maas_api.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/maas_api/basis_maas_api.go -destination=internal/server/implementation/canonical_maas/mocks/mock_basis_maas_api.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	request_body "maas_module/internal/server/implementation/canonical_maas/maas_api/request_body"
	response_body "maas_module/internal/server/implementation/canonical_maas/maas_api/response_body"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBasisMaasAPI is a mock of BasisMaasAPI interface.
type MockBasisMaasAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBasisMaasAPIMockRecorder
	isgomock struct{}
}

// MockBasisMaasAPIMockRecorder is the mock recorder for MockBasisMaasAPI.
type MockBasisMaasAPIMockRecorder struct {
	mock *MockBasisMaasAPI
}

// NewMockBasisMaasAPI creates a new mock instance.
func NewMockBasisMaasAPI(ctrl *gomock.Controller) *MockBasisMaasAPI {
	mock := &MockBasisMaasAPI{ctrl: ctrl}
	mock.recorder = &MockBasisMaasAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasisMaasAPI) EXPECT() *MockBasisMaasAPIMockRecorder {
	return m.recorder
}

// DELETE mocks base method.
func (m *MockBasisMaasAPI) DELETE(ctx context.Context) (response_body.Resbody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DELETE", ctx)
	ret0, _ := ret[0].(response_body.Resbody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETE indicates an expected call of DELETE.
func (mr *MockBasisMaasAPIMockRecorder) DELETE(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETE", reflect.TypeOf((*MockBasisMaasAPI)(nil).DELETE), ctx)
}

// GET mocks base method.
func (m *MockBasisMaasAPI) GET(ctx context.Context) (response_body.Resbody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GET", ctx)
	ret0, _ := ret[0].(response_body.Resbody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GET indicates an expected call of GET.
func (mr *MockBasisMaasAPIMockRecorder) GET(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GET", reflect.TypeOf((*MockBasisMaasAPI)(nil).GET), ctx)
}

// POST mocks base method.
func (m *MockBasisMaasAPI) POST(ctx context.Context, reqBody request_body.Reqbody) (response_body.Resbody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "POST", ctx, reqBody)
	ret0, _ := ret[0].(response_body.Resbody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// POST indicates an expected call of POST.
func (mr *MockBasisMaasAPIMockRecorder) POST(ctx, reqBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "POST", reflect.TypeOf((*MockBasisMaasAPI)(nil).POST), ctx, reqBody)
}

// PUT mocks base method.
func (m *MockBasisMaasAPI) PUT(ctx context.Context, reqBody request_body.Reqbody) (response_body.Resbody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PUT", ctx, reqBody)
	ret0, _ := ret[0].(response_body.Resbody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUT indicates an expected call of PUT.
func (mr *MockBasisMaasAPIMockRecorder) PUT(ctx, reqBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUT", reflect.TypeOf((*MockBasisMaasAPI)(nil).PUT), ctx, reqBody)
}
