// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/maas_api/maas_api_factory.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/maas_api/maas_api_factory.go -destination=internal/server/implementation/canonical_maas/mocks/mock_maas_api_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	maas_api "maas_module/internal/server/interfaces/maas_api"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMaasAPIFactory is a mock of MaasAPIFactory interface.
type MockMaasAPIFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMaasAPIFactoryMockRecorder
	isgomock struct{}
}

// MockMaasAPIFactoryMockRecorder is the mock recorder for MockMaasAPIFactory.
type MockMaasAPIFactoryMockRecorder struct {
	mock *MockMaasAPIFactory
}

// NewMockMaasAPIFactory creates a new mock instance.
func NewMockMaasAPIFactory(ctrl *gomock.Controller) *MockMaasAPIFactory {
	mock := &MockMaasAPIFactory{ctrl: ctrl}
	mock.recorder = &MockMaasAPIFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaasAPIFactory) EXPECT() *MockMaasAPIFactoryMockRecorder {
	return m.recorder
}

// NewFabrics mocks base method.
func (m *MockMaasAPIFactory) NewFabrics(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewFabrics", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewFabrics indicates an expected call of NewFabrics.
func (mr *MockMaasAPIFactoryMockRecorder) NewFabrics(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFabrics", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewFabrics), args...)
}

// NewIPAddressRelease mocks base method.
func (m *MockMaasAPIFactory) NewIPAddressRelease(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIPAddressRelease", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewIPAddressRelease indicates an expected call of NewIPAddressRelease.
func (mr *MockMaasAPIFactoryMockRecorder) NewIPAddressRelease(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIPAddressRelease", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewIPAddressRelease), args...)
}

// NewIPAddressReserve mocks base method.
func (m *MockMaasAPIFactory) NewIPAddressReserve(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIPAddressReserve", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewIPAddressReserve indicates an expected call of NewIPAddressReserve.
func (mr *MockMaasAPIFactoryMockRecorder) NewIPAddressReserve(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIPAddressReserve", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewIPAddressReserve), args...)
}

// NewIPRanges mocks base method.
func (m *MockMaasAPIFactory) NewIPRanges(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIPRanges", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewIPRanges indicates an expected call of NewIPRanges.
func (mr *MockMaasAPIFactoryMockRecorder) NewIPRanges(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIPRanges", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewIPRanges), args...)
}

// NewInterfaceDisconnect mocks base method.
func (m *MockMaasAPIFactory) NewInterfaceDisconnect(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaceDisconnect", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaceDisconnect indicates an expected call of NewInterfaceDisconnect.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaceDisconnect(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaceDisconnect", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaceDisconnect), args...)
}

// NewInterfaceAddTag mocks base method.
func (m *MockMaasAPIFactory) NewInterfaceAddTag(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaceAddTag", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaceAddTag indicates an expected call of NewInterfaceAddTag.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaceAddTag(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaceAddTag", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaceAddTag), args...)
}

// NewInterfaceRemoveTag mocks base method.
func (m *MockMaasAPIFactory) NewInterfaceRemoveTag(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaceRemoveTag", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaceRemoveTag indicates an expected call of NewInterfaceRemoveTag.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaceRemoveTag(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaceRemoveTag", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaceRemoveTag), args...)
}

// NewInterfaceUpdate mocks base method.
func (m *MockMaasAPIFactory) NewInterfaceUpdate(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaceUpdate", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaceUpdate indicates an expected call of NewInterfaceUpdate.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaceUpdate(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaceUpdate", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaceUpdate), args...)
}

// NewInterfaceLink mocks base method.
func (m *MockMaasAPIFactory) NewInterfaceLink(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaceLink", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaceLink indicates an expected call of NewInterfaceLink.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaceLink(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaceLink", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaceLink), args...)
}

// NewInterfaces mocks base method.
func (m *MockMaasAPIFactory) NewInterfaces(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewInterfaces", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewInterfaces indicates an expected call of NewInterfaces.
func (mr *MockMaasAPIFactoryMockRecorder) NewInterfaces(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterfaces", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewInterfaces), args...)
}

// NewMachineAbort mocks base method.
func (m *MockMaasAPIFactory) NewMachineAbort(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineAbort", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineAbort indicates an expected call of NewMachineAbort.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineAbort(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineAbort", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineAbort), args...)
}

// NewMachineCommission mocks base method.
func (m *MockMaasAPIFactory) NewMachineCommission(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineCommission", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineCommission indicates an expected call of NewMachineCommission.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineCommission(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineCommission", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineCommission), args...)
}

// NewMachineDeploy mocks base method.
func (m *MockMaasAPIFactory) NewMachineDeploy(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineDeploy", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineDeploy indicates an expected call of NewMachineDeploy.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineDeploy(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineDeploy", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineDeploy), args...)
}

// NewMachineMarkBroken mocks base method.
func (m *MockMaasAPIFactory) NewMachineMarkBroken(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineMarkBroken", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineMarkBroken indicates an expected call of NewMachineMarkBroken.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineMarkBroken(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineMarkBroken", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineMarkBroken), args...)
}

// NewMachinePowerOFF mocks base method.
func (m *MockMaasAPIFactory) NewMachinePowerOFF(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachinePowerOFF", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachinePowerOFF indicates an expected call of NewMachinePowerOFF.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachinePowerOFF(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachinePowerOFF", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachinePowerOFF), args...)
}

// NewMachinePowerON mocks base method.
func (m *MockMaasAPIFactory) NewMachinePowerON(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachinePowerON", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachinePowerON indicates an expected call of NewMachinePowerON.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachinePowerON(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachinePowerON", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachinePowerON), args...)
}

// NewMachineRelease mocks base method.
func (m *MockMaasAPIFactory) NewMachineRelease(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineRelease", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineRelease indicates an expected call of NewMachineRelease.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineRelease(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineRelease", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineRelease), args...)
}

// NewMachineSystemID mocks base method.
func (m *MockMaasAPIFactory) NewMachineSystemID(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachineSystemID", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachineSystemID indicates an expected call of NewMachineSystemID.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachineSystemID(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachineSystemID", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachineSystemID), args...)
}

// NewMachines mocks base method.
func (m *MockMaasAPIFactory) NewMachines(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMachines", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewMachines indicates an expected call of NewMachines.
func (mr *MockMaasAPIFactoryMockRecorder) NewMachines(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMachines", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewMachines), args...)
}

// NewSubnetUnreservedIPRanges mocks base method.
func (m *MockMaasAPIFactory) NewSubnetUnreservedIPRanges(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewSubnetUnreservedIPRanges", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewSubnetUnreservedIPRanges indicates an expected call of NewSubnetUnreservedIPRanges.
func (mr *MockMaasAPIFactoryMockRecorder) NewSubnetUnreservedIPRanges(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubnetUnreservedIPRanges", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewSubnetUnreservedIPRanges), args...)
}

// NewSubnets mocks base method.
func (m *MockMaasAPIFactory) NewSubnets(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewSubnets", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewSubnets indicates an expected call of NewSubnets.
func (mr *MockMaasAPIFactoryMockRecorder) NewSubnets(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubnets", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewSubnets), args...)
}

// NewVMHostCompose mocks base method.
func (m *MockMaasAPIFactory) NewVMHostCompose(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVMHostCompose", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewVMHostCompose indicates an expected call of NewVMHostCompose.
func (mr *MockMaasAPIFactoryMockRecorder) NewVMHostCompose(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVMHostCompose", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewVMHostCompose), args...)
}

// NewVMHostHostID mocks base method.
func (m *MockMaasAPIFactory) NewVMHostHostID(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVMHostHostID", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewVMHostHostID indicates an expected call of NewVMHostHostID.
func (mr *MockMaasAPIFactoryMockRecorder) NewVMHostHostID(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVMHostHostID", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewVMHostHostID), args...)
}

// NewVMHostParameters mocks base method.
func (m *MockMaasAPIFactory) NewVMHostParameters(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVMHostParameters", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewVMHostParameters indicates an expected call of NewVMHostParameters.
func (mr *MockMaasAPIFactoryMockRecorder) NewVMHostParameters(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVMHostParameters", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewVMHostParameters), args...)
}

// NewVMHostRefresh mocks base method.
func (m *MockMaasAPIFactory) NewVMHostRefresh(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVMHostRefresh", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewVMHostRefresh indicates an expected call of NewVMHostRefresh.
func (mr *MockMaasAPIFactoryMockRecorder) NewVMHostRefresh(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVMHostRefresh", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewVMHostRefresh), args...)
}

// NewVMHosts mocks base method.
func (m *MockMaasAPIFactory) NewVMHosts(args ...any) maas_api.BasisMaasAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewVMHosts", varargs...)
	ret0, _ := ret[0].(maas_api.BasisMaasAPI)
	return ret0
}

// NewVMHosts indicates an expected call of NewVMHosts.
func (mr *MockMaasAPIFactoryMockRecorder) NewVMHosts(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVMHosts", reflect.TypeOf((*MockMaasAPIFactory)(nil).NewVMHosts), args...)
}
