// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/network_interface.proto

package protonetwork

import (
	proto "common/api/proto"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for detail error code
type DetailCode int32

const (
	DetailCode_ZERO                 DetailCode = 0
	DetailCode_IF_PARAMETER_INVALID DetailCode = 41
	DetailCode_UNSUPPORT_PRODUCT    DetailCode = 42
	DetailCode_NW_ENVIRONMENT_ERROR DetailCode = 61
	DetailCode_NW_COMMAND_ERROR     DetailCode = 71
	DetailCode_VSW_VLAN_DUPLICATE   DetailCode = 73
	DetailCode_VSW_VLAN_NOTFOUND    DetailCode = 74
)

// Enum value maps for DetailCode.
var (
	DetailCode_name = map[int32]string{
		0:  "ZERO",
		41: "IF_PARAMETER_INVALID",
		42: "UNSUPPORT_PRODUCT",
		61: "NW_ENVIRONMENT_ERROR",
		71: "NW_COMMAND_ERROR",
		73: "VSW_VLAN_DUPLICATE",
		74: "VSW_VLAN_NOTFOUND",
	}
	DetailCode_value = map[string]int32{
		"ZERO":                 0,
		"IF_PARAMETER_INVALID": 41,
		"UNSUPPORT_PRODUCT":    42,
		"NW_ENVIRONMENT_ERROR": 61,
		"NW_COMMAND_ERROR":     71,
		"VSW_VLAN_DUPLICATE":   73,
		"VSW_VLAN_NOTFOUND":    74,
	}
)

func (x DetailCode) Enum() *DetailCode {
	p := new(DetailCode)
	*p = x
	return p
}

func (x DetailCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetailCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_network_interface_proto_enumTypes[0].Descriptor()
}

func (DetailCode) Type() protoreflect.EnumType {
	return &file_api_proto_network_interface_proto_enumTypes[0]
}

func (x DetailCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetailCode.Descriptor instead.
func (DetailCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{0}
}

// message of Product information
type ProductInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`                              // vendor name
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // product name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // version
	Os            *string                `protobuf:"bytes,4,opt,name=os,proto3,oneof" json:"os,omitempty"`                                // os info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInformation) Reset() {
	*x = ProductInformation{}
	mi := &file_api_proto_network_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInformation) ProtoMessage() {}

func (x *ProductInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInformation.ProtoReflect.Descriptor instead.
func (*ProductInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInformation) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ProductInformation) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProductInformation) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

// message of network information
type NwInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteHost    string                 `protobuf:"bytes,1,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"` // host name or ip address
	RemoteUser    string                 `protobuf:"bytes,2,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"` // login user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NwInformation) Reset() {
	*x = NwInformation{}
	mi := &file_api_proto_network_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NwInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NwInformation) ProtoMessage() {}

func (x *NwInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NwInformation.ProtoReflect.Descriptor instead.
func (*NwInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{1}
}

func (x *NwInformation) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *NwInformation) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

// Request message for VlanAdd
type VlanAddRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	SwitchInfo     *NwInformation         `protobuf:"bytes,2,opt,name=switch_info,json=switchInfo,proto3" json:"switch_info,omitempty"`                   // network switch information
	InterfaceName  string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`          // physical interface name
	VlanType       string                 `protobuf:"bytes,4,opt,name=vlan_type,json=vlanType,proto3" json:"vlan_type,omitempty"`                         // type of vlan(Port or Trunk)
	VlanId         *int32                 `protobuf:"varint,5,opt,name=vlan_id,json=vlanId,proto3,oneof" json:"vlan_id,omitempty"`                        // vlan id
	ExtraParameter *string                `protobuf:"bytes,6,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VlanAddRequest) Reset() {
	*x = VlanAddRequest{}
	mi := &file_api_proto_network_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanAddRequest) ProtoMessage() {}

func (x *VlanAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanAddRequest.ProtoReflect.Descriptor instead.
func (*VlanAddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{2}
}

func (x *VlanAddRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VlanAddRequest) GetSwitchInfo() *NwInformation {
	if x != nil {
		return x.SwitchInfo
	}
	return nil
}

func (x *VlanAddRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *VlanAddRequest) GetVlanType() string {
	if x != nil {
		return x.VlanType
	}
	return ""
}

func (x *VlanAddRequest) GetVlanId() int32 {
	if x != nil && x.VlanId != nil {
		return *x.VlanId
	}
	return 0
}

func (x *VlanAddRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VlanAdd
type VlanAddReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanAddReply) Reset() {
	*x = VlanAddReply{}
	mi := &file_api_proto_network_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanAddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanAddReply) ProtoMessage() {}

func (x *VlanAddReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanAddReply.ProtoReflect.Descriptor instead.
func (*VlanAddReply) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{3}
}

func (x *VlanAddReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VlanAddReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for VlanDelete
type VlanDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	SwitchInfo     *NwInformation         `protobuf:"bytes,2,opt,name=switch_info,json=switchInfo,proto3" json:"switch_info,omitempty"`                   // network switch information
	InterfaceName  string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`          // physical interface name
	VlanId         *int32                 `protobuf:"varint,4,opt,name=vlan_id,json=vlanId,proto3,oneof" json:"vlan_id,omitempty"`                        // vlan id
	ExtraParameter *string                `protobuf:"bytes,5,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VlanDeleteRequest) Reset() {
	*x = VlanDeleteRequest{}
	mi := &file_api_proto_network_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanDeleteRequest) ProtoMessage() {}

func (x *VlanDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanDeleteRequest.ProtoReflect.Descriptor instead.
func (*VlanDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{4}
}

func (x *VlanDeleteRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VlanDeleteRequest) GetSwitchInfo() *NwInformation {
	if x != nil {
		return x.SwitchInfo
	}
	return nil
}

func (x *VlanDeleteRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *VlanDeleteRequest) GetVlanId() int32 {
	if x != nil && x.VlanId != nil {
		return *x.VlanId
	}
	return 0
}

func (x *VlanDeleteRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VlanDelete
type VlanDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanDeleteReply) Reset() {
	*x = VlanDeleteReply{}
	mi := &file_api_proto_network_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanDeleteReply) ProtoMessage() {}

func (x *VlanDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanDeleteReply.ProtoReflect.Descriptor instead.
func (*VlanDeleteReply) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{5}
}

func (x *VlanDeleteReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VlanDeleteReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for VswVlanAdd
type VswVlanAddRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	HostInfo       *NwInformation         `protobuf:"bytes,2,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`                         // host information
	VlanId         *int32                 `protobuf:"varint,3,opt,name=vlan_id,json=vlanId,proto3,oneof" json:"vlan_id,omitempty"`                        // vlan id
	IfName         string                 `protobuf:"bytes,4,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`                               // physical interface name
	ExtraParameter *string                `protobuf:"bytes,5,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VswVlanAddRequest) Reset() {
	*x = VswVlanAddRequest{}
	mi := &file_api_proto_network_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VswVlanAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VswVlanAddRequest) ProtoMessage() {}

func (x *VswVlanAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VswVlanAddRequest.ProtoReflect.Descriptor instead.
func (*VswVlanAddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{6}
}

func (x *VswVlanAddRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VswVlanAddRequest) GetHostInfo() *NwInformation {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *VswVlanAddRequest) GetVlanId() int32 {
	if x != nil && x.VlanId != nil {
		return *x.VlanId
	}
	return 0
}

func (x *VswVlanAddRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *VswVlanAddRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VswVlanAdd
type VswVlanAddReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VswVlanAddReply) Reset() {
	*x = VswVlanAddReply{}
	mi := &file_api_proto_network_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VswVlanAddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VswVlanAddReply) ProtoMessage() {}

func (x *VswVlanAddReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VswVlanAddReply.ProtoReflect.Descriptor instead.
func (*VswVlanAddReply) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{7}
}

func (x *VswVlanAddReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VswVlanAddReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request message for VswVlanDelete
type VswVlanDeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo    *ProductInformation    `protobuf:"bytes,1,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`                // Product information
	HostInfo       *NwInformation         `protobuf:"bytes,2,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`                         // host information
	VlanId         *int32                 `protobuf:"varint,3,opt,name=vlan_id,json=vlanId,proto3,oneof" json:"vlan_id,omitempty"`                        // vlan id
	IfName         string                 `protobuf:"bytes,4,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`                               // physical interface name
	ExtraParameter *string                `protobuf:"bytes,5,opt,name=extra_parameter,json=extraParameter,proto3,oneof" json:"extra_parameter,omitempty"` // Product extension parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VswVlanDeleteRequest) Reset() {
	*x = VswVlanDeleteRequest{}
	mi := &file_api_proto_network_interface_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VswVlanDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VswVlanDeleteRequest) ProtoMessage() {}

func (x *VswVlanDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VswVlanDeleteRequest.ProtoReflect.Descriptor instead.
func (*VswVlanDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{8}
}

func (x *VswVlanDeleteRequest) GetProductInfo() *ProductInformation {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *VswVlanDeleteRequest) GetHostInfo() *NwInformation {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *VswVlanDeleteRequest) GetVlanId() int32 {
	if x != nil && x.VlanId != nil {
		return *x.VlanId
	}
	return 0
}

func (x *VswVlanDeleteRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *VswVlanDeleteRequest) GetExtraParameter() string {
	if x != nil && x.ExtraParameter != nil {
		return *x.ExtraParameter
	}
	return ""
}

// Response message for VswVlanDelete
type VswVlanDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *proto.ResultCode      `protobuf:"varint,1,opt,name=result,proto3,enum=common.ResultCode,oneof" json:"result,omitempty"`   // result of command (SUCCESS or ERROR)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VswVlanDeleteReply) Reset() {
	*x = VswVlanDeleteReply{}
	mi := &file_api_proto_network_interface_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VswVlanDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VswVlanDeleteReply) ProtoMessage() {}

func (x *VswVlanDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_network_interface_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VswVlanDeleteReply.ProtoReflect.Descriptor instead.
func (*VswVlanDeleteReply) Descriptor() ([]byte, []int) {
	return file_api_proto_network_interface_proto_rawDescGZIP(), []int{9}
}

func (x *VswVlanDeleteReply) GetResult() proto.ResultCode {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return proto.ResultCode(0)
}

func (x *VswVlanDeleteReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_network_interface_proto protoreflect.FileDescriptor

const file_api_proto_network_interface_proto_rawDesc = "" +
	"\n" +
	"!api/proto/network_interface.proto\x12\fprotonetwork\x1a\x17validate/validate.proto\x1a'common/api/proto/common_interface.proto\"\xb5\x01\n" +
	"\x12ProductInformation\x12\"\n" +
	"\x06vendor\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\x06vendor\x12-\n" +
	"\fproduct_name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\vproductName\x12$\n" +
	"\aversion\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\aversion\x12\x1f\n" +
	"\x02os\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01H\x00R\x02os\x88\x01\x01B\x05\n" +
	"\x03_os\"h\n" +
	"\rNwInformation\x12+\n" +
	"\vremote_host\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\n" +
	"remoteHost\x12*\n" +
	"\vremote_user\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\n" +
	"remoteUser\"\xf9\x02\n" +
	"\x0eVlanAddRequest\x12M\n" +
	"\fproduct_info\x18\x01 \x01(\v2 .protonetwork.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12F\n" +
	"\vswitch_info\x18\x02 \x01(\v2\x1b.protonetwork.NwInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"switchInfo\x120\n" +
	"\x0einterface_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\rinterfaceName\x12&\n" +
	"\tvlan_type\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x05R\bvlanType\x12(\n" +
	"\avlan_id\x18\x05 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfe\x1f(\x01H\x00R\x06vlanId\x88\x01\x01\x12,\n" +
	"\x0fextra_parameter\x18\x06 \x01(\tH\x01R\x0eextraParameter\x88\x01\x01B\n" +
	"\n" +
	"\b_vlan_idB\x12\n" +
	"\x10_extra_parameter\"o\n" +
	"\fVlanAddReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xd4\x02\n" +
	"\x11VlanDeleteRequest\x12M\n" +
	"\fproduct_info\x18\x01 \x01(\v2 .protonetwork.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12F\n" +
	"\vswitch_info\x18\x02 \x01(\v2\x1b.protonetwork.NwInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"switchInfo\x120\n" +
	"\x0einterface_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18 R\rinterfaceName\x12(\n" +
	"\avlan_id\x18\x04 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfe\x1f(\x01H\x00R\x06vlanId\x88\x01\x01\x12,\n" +
	"\x0fextra_parameter\x18\x05 \x01(\tH\x01R\x0eextraParameter\x88\x01\x01B\n" +
	"\n" +
	"\b_vlan_idB\x12\n" +
	"\x10_extra_parameter\"r\n" +
	"\x0fVlanDeleteReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xc2\x02\n" +
	"\x11VswVlanAddRequest\x12M\n" +
	"\fproduct_info\x18\x01 \x01(\v2 .protonetwork.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12B\n" +
	"\thost_info\x18\x02 \x01(\v2\x1b.protonetwork.NwInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bhostInfo\x12(\n" +
	"\avlan_id\x18\x03 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfe\x1f(\x01H\x00R\x06vlanId\x88\x01\x01\x12\"\n" +
	"\aif_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\aR\x06ifName\x12,\n" +
	"\x0fextra_parameter\x18\x05 \x01(\tH\x01R\x0eextraParameter\x88\x01\x01B\n" +
	"\n" +
	"\b_vlan_idB\x12\n" +
	"\x10_extra_parameter\"r\n" +
	"\x0fVswVlanAddReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result\"\xc5\x02\n" +
	"\x14VswVlanDeleteRequest\x12M\n" +
	"\fproduct_info\x18\x01 \x01(\v2 .protonetwork.ProductInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vproductInfo\x12B\n" +
	"\thost_info\x18\x02 \x01(\v2\x1b.protonetwork.NwInformationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bhostInfo\x12(\n" +
	"\avlan_id\x18\x03 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xfe\x1f(\x01H\x00R\x06vlanId\x88\x01\x01\x12\"\n" +
	"\aif_name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\aR\x06ifName\x12,\n" +
	"\x0fextra_parameter\x18\x05 \x01(\tH\x01R\x0eextraParameter\x88\x01\x01B\n" +
	"\n" +
	"\b_vlan_idB\x12\n" +
	"\x10_extra_parameter\"u\n" +
	"\x12VswVlanDeleteReply\x12/\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.common.ResultCodeH\x00R\x06result\x88\x01\x01\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\t\n" +
	"\a_result*\xa6\x01\n" +
	"\n" +
	"DetailCode\x12\b\n" +
	"\x04ZERO\x10\x00\x12\x18\n" +
	"\x14IF_PARAMETER_INVALID\x10)\x12\x15\n" +
	"\x11UNSUPPORT_PRODUCT\x10*\x12\x18\n" +
	"\x14NW_ENVIRONMENT_ERROR\x10=\x12\x14\n" +
	"\x10NW_COMMAND_ERROR\x10G\x12\x16\n" +
	"\x12VSW_VLAN_DUPLICATE\x10I\x12\x15\n" +
	"\x11VSW_VLAN_NOTFOUND\x10J2\xc9\x02\n" +
	"\aNetwork\x12E\n" +
	"\aVlanAdd\x12\x1c.protonetwork.VlanAddRequest\x1a\x1a.protonetwork.VlanAddReply\"\x00\x12N\n" +
	"\n" +
	"VlanDelete\x12\x1f.protonetwork.VlanDeleteRequest\x1a\x1d.protonetwork.VlanDeleteReply\"\x00\x12N\n" +
	"\n" +
	"VswVlanAdd\x12\x1f.protonetwork.VswVlanAddRequest\x1a\x1d.protonetwork.VswVlanAddReply\"\x00\x12W\n" +
	"\rVswVlanDelete\x12\".protonetwork.VswVlanDeleteRequest\x1a .protonetwork.VswVlanDeleteReply\"\x00B'Z%network_module/api/proto;protonetworkb\x06proto3"

var (
	file_api_proto_network_interface_proto_rawDescOnce sync.Once
	file_api_proto_network_interface_proto_rawDescData []byte
)

func file_api_proto_network_interface_proto_rawDescGZIP() []byte {
	file_api_proto_network_interface_proto_rawDescOnce.Do(func() {
		file_api_proto_network_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_network_interface_proto_rawDesc), len(file_api_proto_network_interface_proto_rawDesc)))
	})
	return file_api_proto_network_interface_proto_rawDescData
}

var file_api_proto_network_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_network_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_network_interface_proto_goTypes = []any{
	(DetailCode)(0),              // 0: protonetwork.DetailCode
	(*ProductInformation)(nil),   // 1: protonetwork.ProductInformation
	(*NwInformation)(nil),        // 2: protonetwork.NwInformation
	(*VlanAddRequest)(nil),       // 3: protonetwork.VlanAddRequest
	(*VlanAddReply)(nil),         // 4: protonetwork.VlanAddReply
	(*VlanDeleteRequest)(nil),    // 5: protonetwork.VlanDeleteRequest
	(*VlanDeleteReply)(nil),      // 6: protonetwork.VlanDeleteReply
	(*VswVlanAddRequest)(nil),    // 7: protonetwork.VswVlanAddRequest
	(*VswVlanAddReply)(nil),      // 8: protonetwork.VswVlanAddReply
	(*VswVlanDeleteRequest)(nil), // 9: protonetwork.VswVlanDeleteRequest
	(*VswVlanDeleteReply)(nil),   // 10: protonetwork.VswVlanDeleteReply
	(proto.ResultCode)(0),        // 11: common.ResultCode
}
var file_api_proto_network_interface_proto_depIdxs = []int32{
	1,  // 0: protonetwork.VlanAddRequest.product_info:type_name -> protonetwork.ProductInformation
	2,  // 1: protonetwork.VlanAddRequest.switch_info:type_name -> protonetwork.NwInformation
	11, // 2: protonetwork.VlanAddReply.result:type_name -> common.ResultCode
	1,  // 3: protonetwork.VlanDeleteRequest.product_info:type_name -> protonetwork.ProductInformation
	2,  // 4: protonetwork.VlanDeleteRequest.switch_info:type_name -> protonetwork.NwInformation
	11, // 5: protonetwork.VlanDeleteReply.result:type_name -> common.ResultCode
	1,  // 6: protonetwork.VswVlanAddRequest.product_info:type_name -> protonetwork.ProductInformation
	2,  // 7: protonetwork.VswVlanAddRequest.host_info:type_name -> protonetwork.NwInformation
	11, // 8: protonetwork.VswVlanAddReply.result:type_name -> common.ResultCode
	1,  // 9: protonetwork.VswVlanDeleteRequest.product_info:type_name -> protonetwork.ProductInformation
	2,  // 10: protonetwork.VswVlanDeleteRequest.host_info:type_name -> protonetwork.NwInformation
	11, // 11: protonetwork.VswVlanDeleteReply.result:type_name -> common.ResultCode
	3,  // 12: protonetwork.Network.VlanAdd:input_type -> protonetwork.VlanAddRequest
	5,  // 13: protonetwork.Network.VlanDelete:input_type -> protonetwork.VlanDeleteRequest
	7,  // 14: protonetwork.Network.VswVlanAdd:input_type -> protonetwork.VswVlanAddRequest
	9,  // 15: protonetwork.Network.VswVlanDelete:input_type -> protonetwork.VswVlanDeleteRequest
	4,  // 16: protonetwork.Network.VlanAdd:output_type -> protonetwork.VlanAddReply
	6,  // 17: protonetwork.Network.VlanDelete:output_type -> protonetwork.VlanDeleteReply
	8,  // 18: protonetwork.Network.VswVlanAdd:output_type -> protonetwork.VswVlanAddReply
	10, // 19: protonetwork.Network.VswVlanDelete:output_type -> protonetwork.VswVlanDeleteReply
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_network_interface_proto_init() }
func file_api_proto_network_interface_proto_init() {
	if File_api_proto_network_interface_proto != nil {
		return
	}
	file_api_proto_network_interface_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_network_interface_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_network_interface_proto_rawDesc), len(file_api_proto_network_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_network_interface_proto_goTypes,
		DependencyIndexes: file_api_proto_network_interface_proto_depIdxs,
		EnumInfos:         file_api_proto_network_interface_proto_enumTypes,
		MessageInfos:      file_api_proto_network_interface_proto_msgTypes,
	}.Build()
	File_api_proto_network_interface_proto = out.File
	file_api_proto_network_interface_proto_goTypes = nil
	file_api_proto_network_interface_proto_depIdxs = nil
}
