// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/network_interface.proto

package protonetwork

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "common/api/proto"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.ResultCode(0)
)

// Validate checks the field values on ProductInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProductInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductInformationMultiError, or nil if none found.
func (m *ProductInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetVendor()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "Vendor",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetProductName()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "ProductName",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetVersion()); l < 1 || l > 128 {
		err := ProductInformationValidationError{
			field:  "Version",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Os != nil {

		if l := utf8.RuneCountInString(m.GetOs()); l < 1 || l > 128 {
			err := ProductInformationValidationError{
				field:  "Os",
				reason: "value length must be between 1 and 128 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ProductInformationMultiError(errors)
	}

	return nil
}

// ProductInformationMultiError is an error wrapping multiple validation errors
// returned by ProductInformation.ValidateAll() if the designated constraints
// aren't met.
type ProductInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductInformationMultiError) AllErrors() []error { return m }

// ProductInformationValidationError is the validation error returned by
// ProductInformation.Validate if the designated constraints aren't met.
type ProductInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductInformationValidationError) ErrorName() string {
	return "ProductInformationValidationError"
}

// Error satisfies the builtin error interface
func (e ProductInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductInformationValidationError{}

// Validate checks the field values on NwInformation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NwInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NwInformation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NwInformationMultiError, or
// nil if none found.
func (m *NwInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *NwInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRemoteHost()); l < 1 || l > 128 {
		err := NwInformationValidationError{
			field:  "RemoteHost",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRemoteUser()); l < 1 || l > 32 {
		err := NwInformationValidationError{
			field:  "RemoteUser",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NwInformationMultiError(errors)
	}

	return nil
}

// NwInformationMultiError is an error wrapping multiple validation errors
// returned by NwInformation.ValidateAll() if the designated constraints
// aren't met.
type NwInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NwInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NwInformationMultiError) AllErrors() []error { return m }

// NwInformationValidationError is the validation error returned by
// NwInformation.Validate if the designated constraints aren't met.
type NwInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NwInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NwInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NwInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NwInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NwInformationValidationError) ErrorName() string { return "NwInformationValidationError" }

// Error satisfies the builtin error interface
func (e NwInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNwInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NwInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NwInformationValidationError{}

// Validate checks the field values on VlanAddRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VlanAddRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VlanAddRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VlanAddRequestMultiError,
// or nil if none found.
func (m *VlanAddRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VlanAddRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := VlanAddRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VlanAddRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VlanAddRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VlanAddRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetSwitchInfo() == nil {
		err := VlanAddRequestValidationError{
			field:  "SwitchInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSwitchInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VlanAddRequestValidationError{
					field:  "SwitchInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VlanAddRequestValidationError{
					field:  "SwitchInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSwitchInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VlanAddRequestValidationError{
				field:  "SwitchInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetInterfaceName()); l < 1 || l > 32 {
		err := VlanAddRequestValidationError{
			field:  "InterfaceName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetVlanType()); l < 1 || l > 5 {
		err := VlanAddRequestValidationError{
			field:  "VlanType",
			reason: "value length must be between 1 and 5 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.VlanId != nil {

		if val := m.GetVlanId(); val < 1 || val > 4094 {
			err := VlanAddRequestValidationError{
				field:  "VlanId",
				reason: "value must be inside range [1, 4094]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return VlanAddRequestMultiError(errors)
	}

	return nil
}

// VlanAddRequestMultiError is an error wrapping multiple validation errors
// returned by VlanAddRequest.ValidateAll() if the designated constraints
// aren't met.
type VlanAddRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VlanAddRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VlanAddRequestMultiError) AllErrors() []error { return m }

// VlanAddRequestValidationError is the validation error returned by
// VlanAddRequest.Validate if the designated constraints aren't met.
type VlanAddRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VlanAddRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VlanAddRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VlanAddRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VlanAddRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VlanAddRequestValidationError) ErrorName() string { return "VlanAddRequestValidationError" }

// Error satisfies the builtin error interface
func (e VlanAddRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVlanAddRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VlanAddRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VlanAddRequestValidationError{}

// Validate checks the field values on VlanAddReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VlanAddReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VlanAddReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VlanAddReplyMultiError, or
// nil if none found.
func (m *VlanAddReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VlanAddReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return VlanAddReplyMultiError(errors)
	}

	return nil
}

// VlanAddReplyMultiError is an error wrapping multiple validation errors
// returned by VlanAddReply.ValidateAll() if the designated constraints aren't met.
type VlanAddReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VlanAddReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VlanAddReplyMultiError) AllErrors() []error { return m }

// VlanAddReplyValidationError is the validation error returned by
// VlanAddReply.Validate if the designated constraints aren't met.
type VlanAddReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VlanAddReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VlanAddReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VlanAddReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VlanAddReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VlanAddReplyValidationError) ErrorName() string { return "VlanAddReplyValidationError" }

// Error satisfies the builtin error interface
func (e VlanAddReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVlanAddReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VlanAddReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VlanAddReplyValidationError{}

// Validate checks the field values on VlanDeleteRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VlanDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VlanDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VlanDeleteRequestMultiError, or nil if none found.
func (m *VlanDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VlanDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := VlanDeleteRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VlanDeleteRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VlanDeleteRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VlanDeleteRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetSwitchInfo() == nil {
		err := VlanDeleteRequestValidationError{
			field:  "SwitchInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSwitchInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VlanDeleteRequestValidationError{
					field:  "SwitchInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VlanDeleteRequestValidationError{
					field:  "SwitchInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSwitchInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VlanDeleteRequestValidationError{
				field:  "SwitchInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetInterfaceName()); l < 1 || l > 32 {
		err := VlanDeleteRequestValidationError{
			field:  "InterfaceName",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.VlanId != nil {

		if val := m.GetVlanId(); val < 1 || val > 4094 {
			err := VlanDeleteRequestValidationError{
				field:  "VlanId",
				reason: "value must be inside range [1, 4094]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return VlanDeleteRequestMultiError(errors)
	}

	return nil
}

// VlanDeleteRequestMultiError is an error wrapping multiple validation errors
// returned by VlanDeleteRequest.ValidateAll() if the designated constraints
// aren't met.
type VlanDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VlanDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VlanDeleteRequestMultiError) AllErrors() []error { return m }

// VlanDeleteRequestValidationError is the validation error returned by
// VlanDeleteRequest.Validate if the designated constraints aren't met.
type VlanDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VlanDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VlanDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VlanDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VlanDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VlanDeleteRequestValidationError) ErrorName() string {
	return "VlanDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VlanDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVlanDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VlanDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VlanDeleteRequestValidationError{}

// Validate checks the field values on VlanDeleteReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VlanDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VlanDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VlanDeleteReplyMultiError, or nil if none found.
func (m *VlanDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VlanDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return VlanDeleteReplyMultiError(errors)
	}

	return nil
}

// VlanDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by VlanDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type VlanDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VlanDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VlanDeleteReplyMultiError) AllErrors() []error { return m }

// VlanDeleteReplyValidationError is the validation error returned by
// VlanDeleteReply.Validate if the designated constraints aren't met.
type VlanDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VlanDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VlanDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VlanDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VlanDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VlanDeleteReplyValidationError) ErrorName() string { return "VlanDeleteReplyValidationError" }

// Error satisfies the builtin error interface
func (e VlanDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVlanDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VlanDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VlanDeleteReplyValidationError{}

// Validate checks the field values on VswVlanAddRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VswVlanAddRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VswVlanAddRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VswVlanAddRequestMultiError, or nil if none found.
func (m *VswVlanAddRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VswVlanAddRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := VswVlanAddRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VswVlanAddRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VswVlanAddRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VswVlanAddRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetHostInfo() == nil {
		err := VswVlanAddRequestValidationError{
			field:  "HostInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHostInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VswVlanAddRequestValidationError{
					field:  "HostInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VswVlanAddRequestValidationError{
					field:  "HostInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHostInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VswVlanAddRequestValidationError{
				field:  "HostInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetIfName()); l < 1 || l > 7 {
		err := VswVlanAddRequestValidationError{
			field:  "IfName",
			reason: "value length must be between 1 and 7 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.VlanId != nil {

		if val := m.GetVlanId(); val < 1 || val > 4094 {
			err := VswVlanAddRequestValidationError{
				field:  "VlanId",
				reason: "value must be inside range [1, 4094]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return VswVlanAddRequestMultiError(errors)
	}

	return nil
}

// VswVlanAddRequestMultiError is an error wrapping multiple validation errors
// returned by VswVlanAddRequest.ValidateAll() if the designated constraints
// aren't met.
type VswVlanAddRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VswVlanAddRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VswVlanAddRequestMultiError) AllErrors() []error { return m }

// VswVlanAddRequestValidationError is the validation error returned by
// VswVlanAddRequest.Validate if the designated constraints aren't met.
type VswVlanAddRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VswVlanAddRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VswVlanAddRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VswVlanAddRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VswVlanAddRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VswVlanAddRequestValidationError) ErrorName() string {
	return "VswVlanAddRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VswVlanAddRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVswVlanAddRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VswVlanAddRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VswVlanAddRequestValidationError{}

// Validate checks the field values on VswVlanAddReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VswVlanAddReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VswVlanAddReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VswVlanAddReplyMultiError, or nil if none found.
func (m *VswVlanAddReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VswVlanAddReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return VswVlanAddReplyMultiError(errors)
	}

	return nil
}

// VswVlanAddReplyMultiError is an error wrapping multiple validation errors
// returned by VswVlanAddReply.ValidateAll() if the designated constraints
// aren't met.
type VswVlanAddReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VswVlanAddReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VswVlanAddReplyMultiError) AllErrors() []error { return m }

// VswVlanAddReplyValidationError is the validation error returned by
// VswVlanAddReply.Validate if the designated constraints aren't met.
type VswVlanAddReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VswVlanAddReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VswVlanAddReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VswVlanAddReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VswVlanAddReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VswVlanAddReplyValidationError) ErrorName() string { return "VswVlanAddReplyValidationError" }

// Error satisfies the builtin error interface
func (e VswVlanAddReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVswVlanAddReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VswVlanAddReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VswVlanAddReplyValidationError{}

// Validate checks the field values on VswVlanDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VswVlanDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VswVlanDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VswVlanDeleteRequestMultiError, or nil if none found.
func (m *VswVlanDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VswVlanDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProductInfo() == nil {
		err := VswVlanDeleteRequestValidationError{
			field:  "ProductInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProductInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VswVlanDeleteRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VswVlanDeleteRequestValidationError{
					field:  "ProductInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VswVlanDeleteRequestValidationError{
				field:  "ProductInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetHostInfo() == nil {
		err := VswVlanDeleteRequestValidationError{
			field:  "HostInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHostInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VswVlanDeleteRequestValidationError{
					field:  "HostInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VswVlanDeleteRequestValidationError{
					field:  "HostInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHostInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VswVlanDeleteRequestValidationError{
				field:  "HostInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetIfName()); l < 1 || l > 7 {
		err := VswVlanDeleteRequestValidationError{
			field:  "IfName",
			reason: "value length must be between 1 and 7 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.VlanId != nil {

		if val := m.GetVlanId(); val < 1 || val > 4094 {
			err := VswVlanDeleteRequestValidationError{
				field:  "VlanId",
				reason: "value must be inside range [1, 4094]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ExtraParameter != nil {
		// no validation rules for ExtraParameter
	}

	if len(errors) > 0 {
		return VswVlanDeleteRequestMultiError(errors)
	}

	return nil
}

// VswVlanDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by VswVlanDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type VswVlanDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VswVlanDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VswVlanDeleteRequestMultiError) AllErrors() []error { return m }

// VswVlanDeleteRequestValidationError is the validation error returned by
// VswVlanDeleteRequest.Validate if the designated constraints aren't met.
type VswVlanDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VswVlanDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VswVlanDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VswVlanDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VswVlanDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VswVlanDeleteRequestValidationError) ErrorName() string {
	return "VswVlanDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VswVlanDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVswVlanDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VswVlanDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VswVlanDeleteRequestValidationError{}

// Validate checks the field values on VswVlanDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VswVlanDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VswVlanDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VswVlanDeleteReplyMultiError, or nil if none found.
func (m *VswVlanDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VswVlanDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ErrorMessage

	if m.Result != nil {
		// no validation rules for Result
	}

	if len(errors) > 0 {
		return VswVlanDeleteReplyMultiError(errors)
	}

	return nil
}

// VswVlanDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by VswVlanDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type VswVlanDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VswVlanDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VswVlanDeleteReplyMultiError) AllErrors() []error { return m }

// VswVlanDeleteReplyValidationError is the validation error returned by
// VswVlanDeleteReply.Validate if the designated constraints aren't met.
type VswVlanDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VswVlanDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VswVlanDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VswVlanDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VswVlanDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VswVlanDeleteReplyValidationError) ErrorName() string {
	return "VswVlanDeleteReplyValidationError"
}

// Error satisfies the builtin error interface
func (e VswVlanDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVswVlanDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VswVlanDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VswVlanDeleteReplyValidationError{}
