// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/network_interface.proto

package protonetwork

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Network_VlanAdd_FullMethodName       = "/protonetwork.Network/VlanAdd"
	Network_VlanDelete_FullMethodName    = "/protonetwork.Network/VlanDelete"
	Network_VswVlanAdd_FullMethodName    = "/protonetwork.Network/VswVlanAdd"
	Network_VswVlanDelete_FullMethodName = "/protonetwork.Network/VswVlanDelete"
)

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define service for network
type NetworkClient interface {
	VlanAdd(ctx context.Context, in *VlanAddRequest, opts ...grpc.CallOption) (*VlanAddReply, error)
	VlanDelete(ctx context.Context, in *VlanDeleteRequest, opts ...grpc.CallOption) (*VlanDeleteReply, error)
	VswVlanAdd(ctx context.Context, in *VswVlanAddRequest, opts ...grpc.CallOption) (*VswVlanAddReply, error)
	VswVlanDelete(ctx context.Context, in *VswVlanDeleteRequest, opts ...grpc.CallOption) (*VswVlanDeleteReply, error)
}

type networkClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkClient(cc grpc.ClientConnInterface) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) VlanAdd(ctx context.Context, in *VlanAddRequest, opts ...grpc.CallOption) (*VlanAddReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VlanAddReply)
	err := c.cc.Invoke(ctx, Network_VlanAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) VlanDelete(ctx context.Context, in *VlanDeleteRequest, opts ...grpc.CallOption) (*VlanDeleteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VlanDeleteReply)
	err := c.cc.Invoke(ctx, Network_VlanDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) VswVlanAdd(ctx context.Context, in *VswVlanAddRequest, opts ...grpc.CallOption) (*VswVlanAddReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VswVlanAddReply)
	err := c.cc.Invoke(ctx, Network_VswVlanAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) VswVlanDelete(ctx context.Context, in *VswVlanDeleteRequest, opts ...grpc.CallOption) (*VswVlanDeleteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VswVlanDeleteReply)
	err := c.cc.Invoke(ctx, Network_VswVlanDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
// All implementations must embed UnimplementedNetworkServer
// for forward compatibility.
//
// Define service for network
type NetworkServer interface {
	VlanAdd(context.Context, *VlanAddRequest) (*VlanAddReply, error)
	VlanDelete(context.Context, *VlanDeleteRequest) (*VlanDeleteReply, error)
	VswVlanAdd(context.Context, *VswVlanAddRequest) (*VswVlanAddReply, error)
	VswVlanDelete(context.Context, *VswVlanDeleteRequest) (*VswVlanDeleteReply, error)
	mustEmbedUnimplementedNetworkServer()
}

// UnimplementedNetworkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkServer struct{}

func (UnimplementedNetworkServer) VlanAdd(context.Context, *VlanAddRequest) (*VlanAddReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VlanAdd not implemented")
}
func (UnimplementedNetworkServer) VlanDelete(context.Context, *VlanDeleteRequest) (*VlanDeleteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VlanDelete not implemented")
}
func (UnimplementedNetworkServer) VswVlanAdd(context.Context, *VswVlanAddRequest) (*VswVlanAddReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VswVlanAdd not implemented")
}
func (UnimplementedNetworkServer) VswVlanDelete(context.Context, *VswVlanDeleteRequest) (*VswVlanDeleteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VswVlanDelete not implemented")
}
func (UnimplementedNetworkServer) mustEmbedUnimplementedNetworkServer() {}
func (UnimplementedNetworkServer) testEmbeddedByValue()                 {}

// UnsafeNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServer will
// result in compilation errors.
type UnsafeNetworkServer interface {
	mustEmbedUnimplementedNetworkServer()
}

func RegisterNetworkServer(s grpc.ServiceRegistrar, srv NetworkServer) {
	// If the following call panics, it indicates UnimplementedNetworkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Network_ServiceDesc, srv)
}

func _Network_VlanAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VlanAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).VlanAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_VlanAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).VlanAdd(ctx, req.(*VlanAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_VlanDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VlanDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).VlanDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_VlanDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).VlanDelete(ctx, req.(*VlanDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_VswVlanAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VswVlanAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).VswVlanAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_VswVlanAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).VswVlanAdd(ctx, req.(*VswVlanAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_VswVlanDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VswVlanDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).VswVlanDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_VswVlanDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).VswVlanDelete(ctx, req.(*VswVlanDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Network_ServiceDesc is the grpc.ServiceDesc for Network service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Network_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protonetwork.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VlanAdd",
			Handler:    _Network_VlanAdd_Handler,
		},
		{
			MethodName: "VlanDelete",
			Handler:    _Network_VlanDelete_Handler,
		},
		{
			MethodName: "VswVlanAdd",
			Handler:    _Network_VswVlanAdd_Handler,
		},
		{
			MethodName: "VswVlanDelete",
			Handler:    _Network_VswVlanDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/network_interface.proto",
}
