apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "exporter") }}-service
  labels:
    app: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "exporter") }}-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "exporter") }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.metrics.port }}
  type: {{ .Values.service.type }}
