apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "maas") }}-config
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  MAAS_SERVER_PORT: {{ .Values.config.serverPort | quote }}
  VM_HOST_DISK: {{ .Values.config.vmHostDisk | quote }}
  LXD_PORT: {{ .Values.config.lxdListenPort | quote }}
  ANSIBLE_PATH: {{ .Values.config.ansiblePath | quote }}
  SSH_KEY: {{ .Values.config.sshPrivateKeyPath | quote }}
  TLS_ENABLE: {{ .Values.tls.enabled | quote }}
  TLS_CERT_PATH: {{ .Values.tls.certPath | quote }}
