// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/database.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/database.go -destination=internal/server/interfaces/mocks/mock_database.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "log_module/internal/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Finalize mocks base method.
func (m *MockDatabase) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockDatabaseMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockDatabase)(nil).Finalize))
}

// Init mocks base method.
func (m *MockDatabase) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDatabaseMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDatabase)(nil).Init))
}

// SelectCDITable mocks base method.
func (m *MockDatabase) SelectCDITable() ([]interfaces.CDITargetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCDITable")
	ret0, _ := ret[0].([]interfaces.CDITargetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCDITable indicates an expected call of SelectCDITable.
func (mr *MockDatabaseMockRecorder) SelectCDITable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCDITable", reflect.TypeOf((*MockDatabase)(nil).SelectCDITable))
}

// SelectMaasTable mocks base method.
func (m *MockDatabase) SelectMaasTable() ([]interfaces.MaasServerTargetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectMaasTable")
	ret0, _ := ret[0].([]interfaces.MaasServerTargetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectMaasTable indicates an expected call of SelectMaasTable.
func (mr *MockDatabaseMockRecorder) SelectMaasTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectMaasTable", reflect.TypeOf((*MockDatabase)(nil).SelectMaasTable))
}

// SelectServerTable mocks base method.
func (m *MockDatabase) SelectServerTable() ([]interfaces.IPMITargetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectServerTable")
	ret0, _ := ret[0].([]interfaces.IPMITargetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectServerTable indicates an expected call of SelectServerTable.
func (mr *MockDatabaseMockRecorder) SelectServerTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectServerTable", reflect.TypeOf((*MockDatabase)(nil).SelectServerTable))
}
