// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/cdi.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/cdi.go -destination=internal/server/interfaces/mocks/mock_cdi.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "log_module/internal/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCDI is a mock of CDI interface.
type MockCDI struct {
	ctrl     *gomock.Controller
	recorder *MockCDIMockRecorder
	isgomock struct{}
}

// MockCDIMockRecorder is the mock recorder for MockCDI.
type MockCDIMockRecorder struct {
	mock *MockCDI
}

// NewMockCDI creates a new mock instance.
func NewMockCDI(ctrl *gomock.Controller) *MockCDI {
	mock := &MockCDI{ctrl: ctrl}
	mock.recorder = &MockCDIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDI) EXPECT() *MockCDIMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockCDI) Collection(targetList []interfaces.CDITargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collection", targetList)
}

// Collection indicates an expected call of Collection.
func (mr *MockCDIMockRecorder) Collection(targetList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockCDI)(nil).Collection), targetList)
}

// Finalize mocks base method.
func (m *MockCDI) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockCDIMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockCDI)(nil).Finalize))
}

// Init mocks base method.
func (m *MockCDI) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCDIMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCDI)(nil).Init))
}
