// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/api.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/api.go -destination=internal/server/interfaces/mocks/mock_api.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// APIExecuteJWTAUth mocks base method.
func (m *MockAPI) APIExecuteJWTAUth(ctx context.Context, method, url, apiname, jwt, queryParameter string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIExecuteJWTAUth", ctx, method, url, apiname, jwt, queryParameter)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIExecuteJWTAUth indicates an expected call of APIExecuteJWTAUth.
func (mr *MockAPIMockRecorder) APIExecuteJWTAUth(ctx, method, url, apiname, jwt, queryParameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIExecuteJWTAUth", reflect.TypeOf((*MockAPI)(nil).APIExecuteJWTAUth), ctx, method, url, apiname, jwt, queryParameter)
}

// APIExecuteUserAuth mocks base method.
func (m *MockAPI) APIExecuteUserAuth(ctx context.Context, method, url, apiname, loginUser, loginPass, queryParameter string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIExecuteUserAuth", ctx, method, url, apiname, loginUser, loginPass, queryParameter)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIExecuteUserAuth indicates an expected call of APIExecuteUserAuth.
func (mr *MockAPIMockRecorder) APIExecuteUserAuth(ctx, method, url, apiname, loginUser, loginPass, queryParameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIExecuteUserAuth", reflect.TypeOf((*MockAPI)(nil).APIExecuteUserAuth), ctx, method, url, apiname, loginUser, loginPass, queryParameter)
}
