// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/ipmi.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/ipmi.go -destination=internal/server/interfaces/mocks/mock_ipmi.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "log_module/internal/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPMI is a mock of IPMI interface.
type MockIPMI struct {
	ctrl     *gomock.Controller
	recorder *MockIPMIMockRecorder
	isgomock struct{}
}

// MockIPMIMockRecorder is the mock recorder for MockIPMI.
type MockIPMIMockRecorder struct {
	mock *MockIPMI
}

// NewMockIPMI creates a new mock instance.
func NewMockIPMI(ctrl *gomock.Controller) *MockIPMI {
	mock := &MockIPMI{ctrl: ctrl}
	mock.recorder = &MockIPMIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPMI) EXPECT() *MockIPMIMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockIPMI) Collection(targetList []interfaces.IPMITargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collection", targetList)
}

// Collection indicates an expected call of Collection.
func (mr *MockIPMIMockRecorder) Collection(targetList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockIPMI)(nil).Collection), targetList)
}

// Finalize mocks base method.
func (m *MockIPMI) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockIPMIMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockIPMI)(nil).Finalize))
}

// Init mocks base method.
func (m *MockIPMI) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockIPMIMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIPMI)(nil).Init))
}
