// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/maas_server.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/maas_server.go -destination=internal/server/interfaces/mocks/mock_maas_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "log_module/internal/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMaasServer is a mock of MaasServer interface.
type MockMaasServer struct {
	ctrl     *gomock.Controller
	recorder *MockMaasServerMockRecorder
	isgomock struct{}
}

// MockMaasServerMockRecorder is the mock recorder for MockMaasServer.
type MockMaasServerMockRecorder struct {
	mock *MockMaasServer
}

// NewMockMaasServer creates a new mock instance.
func NewMockMaasServer(ctrl *gomock.Controller) *MockMaasServer {
	mock := &MockMaasServer{ctrl: ctrl}
	mock.recorder = &MockMaasServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaasServer) EXPECT() *MockMaasServerMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockMaasServer) Collection(targetList []interfaces.MaasServerTargetList) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collection", targetList)
}

// Collection indicates an expected call of Collection.
func (mr *MockMaasServerMockRecorder) Collection(targetList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockMaasServer)(nil).Collection), targetList)
}

// Finalize mocks base method.
func (m *MockMaasServer) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockMaasServerMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockMaasServer)(nil).Finalize))
}

// Init mocks base method.
func (m *MockMaasServer) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockMaasServerMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockMaasServer)(nil).Init))
}
