// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/logging.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/logging.go -destination=internal/server/interfaces/mocks/mock_logging.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "log_module/internal/server/interfaces"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogging is a mock of Logging interface.
type MockLogging struct {
	ctrl     *gomock.Controller
	recorder *MockLoggingMockRecorder
	isgomock struct{}
}

// MockLoggingMockRecorder is the mock recorder for MockLogging.
type MockLoggingMockRecorder struct {
	mock *MockLogging
}

// NewMockLogging creates a new mock instance.
func NewMockLogging(ctrl *gomock.Controller) *MockLogging {
	mock := &MockLogging{ctrl: ctrl}
	mock.recorder = &MockLoggingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogging) EXPECT() *MockLoggingMockRecorder {
	return m.recorder
}

// Finalize mocks base method.
func (m *MockLogging) Finalize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finalize")
}

// Finalize indicates an expected call of Finalize.
func (mr *MockLoggingMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockLogging)(nil).Finalize))
}

// Init mocks base method.
func (m *MockLogging) Init(loggingConfig interfaces.LoggingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", loggingConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockLoggingMockRecorder) Init(loggingConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockLogging)(nil).Init), loggingConfig)
}

// Write mocks base method.
func (m *MockLogging) Write(keyId, json string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", keyId, json)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockLoggingMockRecorder) Write(keyId, json any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLogging)(nil).Write), keyId, json)
}
