// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/interfaces/ansible.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/interfaces/ansible.go -destination=internal/server/interfaces/mocks/mock_ansible.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAnsible is a mock of Ansible interface.
type MockAnsible struct {
	ctrl     *gomock.Controller
	recorder *MockAnsibleMockRecorder
	isgomock struct{}
}

// MockAnsibleMockRecorder is the mock recorder for MockAnsible.
type MockAnsibleMockRecorder struct {
	mock *MockAnsible
}

// NewMockAnsible creates a new mock instance.
func NewMockAnsible(ctrl *gomock.Controller) *MockAnsible {
	mock := &MockAnsible{ctrl: ctrl}
	mock.recorder = &MockAnsibleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnsible) EXPECT() *MockAnsibleMockRecorder {
	return m.recorder
}

// CmdExecute mocks base method.
func (m *MockAnsible) CmdExecute(ctx context.Context, remoteHost, remotUser, playbook, extraArgs string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdExecute", ctx, remoteHost, remotUser, playbook, extraArgs)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CmdExecute indicates an expected call of CmdExecute.
func (mr *MockAnsibleMockRecorder) CmdExecute(ctx, remoteHost, remotUser, playbook, extraArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdExecute", reflect.TypeOf((*MockAnsible)(nil).CmdExecute), ctx, remoteHost, remotUser, playbook, extraArgs)
}
