apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "cdi") }}-pg-cdi-model-mappings
  labels:
    app: {{ include "mychart.childName" (dict "Release" .Release "childChartName" "cdi") }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mappings.json: |
    {
      "a100": "NVIDIA-A100-PCIE-80GB",
      "a100_linked": "NVIDIA-A100-PCIE-80GB",
      "a100-40": "NVIDIA-A100-PCIE-40GB",
      "a100-40_linked": "NVIDIA-A100-PCIE-40GB",
      "H100": "NVIDIA-H100-PCIE-80GB",
      "H100_linked": "NVIDIA-H100-PCIE-80GB",
      "H100-NVL": "NVIDIA-H100-NVL-PCIE-94GB",
      "H100-NVL_linked": "NVIDIA-H100-NVL-PCIE-94GB",
      "L40S": "NVIDIA-L40S-PCIE-48GB",
      "Tesla_T4": "NVIDIA-TESLA-T4-PCIE-16GB",
      "BLACKWELL": "NVIDIA-BLACKWELL",
      "BLACKWELL_linked": "NVIDIA-BLACKWELL",
      "MT2892": "NVIDIA-CONNECTX-6-DX",
      "MT2910": "NVIDIA-CONNECTX-7"
    }
