{{- range .Values.secretAccess }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Name }}-secret-reader
  namespace: {{ .namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .secretName }}"]
  verbs: ["get"]
{{- end }}
