{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.childName" (dict "Release" $.Release "childChartName" .name) }}-sa
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "mychart.childName" (dict "Release" $.Release "childChartName" .name) }}
{{- end }}
